window.FAILURES = [
  // ══════════ TECHNOLOGY ══════════
  {
    id: "jobs", name: "Steve Jobs", initials: "SJ", color: "#0ea5e9", category: "Technology",
    fail: "Ousted from Apple in 1985", year: "1985–1997",
    img: "Steve_Jobs_Headshot_2010_(cropped_5).jpg",
    story: "After clashing with the board and CEO John Sculley, Jobs was stripped of operational power and resigned from Apple — the company he co-founded. He founded NeXT and bought Pixar. In 1997 Apple, near collapse, bought NeXT and brought him back. He then led the run of iMac, iPod, iPhone and iPad.",
    whatTheyDid: "Used the exile to build new skills (NeXT software, Pixar storytelling/design). Returned with a clearer product and design philosophy. Cut the product line ruthlessly and bet on a few big ideas.",
    apply: ["Treat a forced exit as a sabbatical to learn something you couldn’t inside the old role.", "When you return (or start again), simplify: fewer projects, higher standards.", "Document what the old environment got wrong so you don’t repeat it."],
    scenariosYes: ["Laid off or pushed out of a company you care about", "Side project that could become the main thing", "Coming back to a team that failed without you"],
    scenariosNo: ["Using ‘I’ll show them’ as the only motivation", "Ignoring legitimate feedback that got you removed"],
    resources: ["Time away from the old org", "A small team or solo capacity to ship something", "Willingness to kill weak products"],
    takeaway: "Getting fired can be the best thing if you use the gap to build capability and clarity — then return or restart with focus.",
    book: "Steve Jobs — Walter Isaacson",
    bookGain: "A full picture of how taste, focus, and brutal prioritization compound — plus the cost of that intensity on people around him. You leave with a sharper sense of product standards and when to say no."
  },
  {
    id: "musk", name: "Elon Musk", initials: "EM", color: "#8b5cf6", category: "Technology",
    fail: "Tesla & SpaceX nearly bankrupt (2008)", year: "2008",
    img: "Elon_Musk_Royal_Society_(crop2).jpg",
    story: "In late 2008 both Tesla and SpaceX were weeks from failure. The financial crisis hit, the Roadster had production issues, and SpaceX had failed launches. Musk put in remaining personal capital and negotiated critical deals. Both companies survived and later defined their industries.",
    whatTheyDid: "Concentrated remaining capital on the single most important milestones. Personally sold the vision to keep employees and investors. Refused to shut one company to save the other until the last possible moment.",
    apply: ["When two big bets are both dying, pick the minimum viable survival path for each.", "Put skin in the game visibly; it changes how partners respond.", "Negotiate hard on the one deal that unlocks the next 12 months."],
    scenariosYes: ["Startup runway under 6 months", "Two products both needing a win", "Crisis where only personal commitment unlocks partners"],
    scenariosNo: ["Burning personal money with no clear milestone", "Ignoring unit economics forever"],
    resources: ["Personal capital or equivalent commitment", "A clear ‘survive 12 months’ plan", "Key customers or partners who can say yes quickly"],
    takeaway: "Near-death is often the filter: the people and plans that survive it are sharper.",
    book: "Elon Musk — Walter Isaacson",
    bookGain: "How extreme first-principles thinking and work intensity look in practice — and where they break teams. Useful for calibrating risk, timelines, and what ‘all-in’ actually costs."
  },
  {
    id: "gates", name: "Bill Gates", initials: "BG", color: "#22c55e", category: "Technology",
    fail: "Traf-O-Data flopped", year: "1972–1975",
    img: "Bill_Gates_2017_(cropped).jpg",
    story: "Gates and Paul Allen’s first company, Traf-O-Data, aimed to process traffic-counter tapes. The business never took off commercially. The technical and partnership lessons fed directly into the founding of Microsoft.",
    whatTheyDid: "Kept the partnership and the habit of shipping software. Moved to a bigger opportunity (microcomputer software) instead of clinging to the first idea.",
    apply: ["Treat the first company as a learning product, not your identity.", "Preserve the team and the shipping muscle; change the market.", "Write down what didn’t work so the next venture doesn’t repeat it."],
    scenariosYes: ["First startup that didn’t find customers", "Technical project with no market fit"],
    scenariosNo: ["Blaming the market without testing a new offer", "Abandoning a co-founder over one failure"],
    resources: ["A partner you still trust", "Basic technical skills", "Willingness to change domain"],
    takeaway: "A failed first company is often the tuition for the one that works.",
    book: "Idea Man — Paul Allen",
    bookGain: "The co-founder’s view of early Microsoft and pre-Microsoft experiments — partnership dynamics, timing the personal computer wave, and why the second act mattered more than the first."
  },
  {
    id: "ma", name: "Jack Ma", initials: "JM", color: "#f59e0b", category: "Technology",
    fail: "Dozens of job rejections; failed early ventures", year: "1980s–1999",
    img: "Jack_Ma_2015.jpg",
    story: "Failed university entrance exams multiple times, was rejected by KFC and many employers, and had early internet ventures that struggled. In 1999 he founded Alibaba with a small team in his apartment.",
    whatTheyDid: "Kept applying and teaching English to stay liquid. Bet on the internet when China was early. Built trust with SMEs instead of chasing only big brands.",
    apply: ["Rejection volume is data — keep a simple pipeline of applications or pitches.", "Use a survival job that still builds skill.", "Pick an underserved customer segment others ignore."],
    scenariosYes: ["High rejection rate in job or investor search", "Building in an emerging market"],
    scenariosNo: ["Applying randomly with no feedback loop", "Copying models without local adaptation"],
    resources: ["Persistence system (weekly targets)", "A small founding team", "Local customer access"],
    takeaway: "Mass rejection is normal before a non-obvious opportunity clicks.",
    book: "Alibaba: The House That Jack Ma Built — Duncan Clark",
    bookGain: "How Alibaba was built under constraint: SME focus, trust systems, and navigating China-scale competition. Practical for platform and marketplace builders."
  },
  {
    id: "chesky", name: "Brian Chesky", initials: "BC", color: "#ff5a5f", category: "Technology",
    fail: "Airbnb nearly dead; sold cereal to survive", year: "2008–2009",
    story: "Investors passed. To fund the company the founders designed and sold Obama O’s and Cap’n McCain’s cereal. That scramble kept them alive until product-market fit and funding arrived.",
    whatTheyDid: "Did unscalable things (cereal, door-to-door hosting help) to learn and to survive. Focused on a few cities and perfecting the host/guest experience.",
    apply: ["When runway is zero, invent a short-term cash product even if it’s weird.", "Do things that don’t scale until you understand the customer.", "Use the survival story later — it becomes culture."],
    scenariosYes: ["Pre-seed with no investors", "Need to learn demand before building more product"],
    scenariosNo: ["Side hustle as a permanent substitute for the core product"],
    resources: ["Creativity under constraint", "Willingness to look silly", "Direct customer contact"],
    takeaway: "Unscalable hustle is often the bridge to a scalable product.",
    book: "The Airbnb Story — Leigh Gallagher",
    bookGain: "How design-led founders found product-market fit through hospitality details, city-by-city growth, and turning rejection into lore. Strong on early-stage creativity."
  },
  {
    id: "bezos", name: "Jeff Bezos", initials: "JB", color: "#ff9900", category: "Technology",
    fail: "Years of Amazon losses and skepticism", year: "1990s–2000s",
    img: "Jeff_Bezos_2016.jpg",
    story: "Amazon lost money for years while expanding categories and building infrastructure. Analysts repeatedly questioned whether it would ever be a real profitable retailer. Bezos kept investing in scale and customer experience.",
    whatTheyDid: "Publicly committed to long-term thinking. Measured customer metrics obsessively. Expanded only when the flywheel justified it.",
    apply: ["Separate losing money by design from losing money by accident.", "Communicate the long-term thesis so stakeholders don’t panic every quarter.", "Invest in infrastructure that gets cheaper per unit as you grow."],
    scenariosYes: ["Marketplace or platform with network effects", "Investors who understand multi-year payback"],
    scenariosNo: ["Burning cash with no path to unit economics"],
    resources: ["Patient capital", "Clear unit-economics model", "Customer obsession metrics"],
    takeaway: "Strategic losses are different from uncontrolled losses — but you must explain the difference.",
    book: "The Everything Store — Brad Stone",
    bookGain: "How Amazon’s flywheel, customer obsession, and high-velocity decision culture were built — including the human and competitive costs. Essential for operators of scale businesses."
  },
  {
    id: "hoffman", name: "Reid Hoffman", initials: "RH", color: "#0a66c2", category: "Technology",
    fail: "SocialNet failed before LinkedIn", year: "1997–2002",
    story: "Hoffman’s first social network, SocialNet, didn’t take off. He later co-founded LinkedIn, applying lessons about networks, professional identity, and timing.",
    whatTheyDid: "Studied why the first product failed. Focused LinkedIn on professional utility and weak ties. Built for network effects deliberately.",
    apply: ["Write a post-mortem of the failed product before the next one.", "Pick a use-case with clear economic value (jobs, deals).", "Design for network density early."],
    scenariosYes: ["Second-time founder", "Social/network products"],
    scenariosNo: ["Copying a network without a sharp use-case"],
    resources: ["User research on why v1 failed", "A wedge use-case", "Patience for network growth"],
    takeaway: "Failed networks teach you which edges actually matter.",
    book: "The Startup of You — Reid Hoffman & Ben Casnocha",
    bookGain: "How to treat your career like a startup: alliances, soft assets, and permanent beta. Practical frameworks for professionals, not only founders."
  },
  {
    id: "page", name: "Larry Page & Sergey Brin", initials: "PB", color: "#4285f4", category: "Technology",
    fail: "Search was ‘already done’; early Google ignored", year: "1996–1999",
    story: "Many believed search was a solved, low-value problem dominated by portals. Page and Brin’s academic project was undervalued until PageRank and focus on relevance proved otherwise.",
    whatTheyDid: "Stuck to relevance as the product. Resisted becoming a portal. Scaled infrastructure ahead of demand.",
    apply: ["Question ‘the market is done’ claims with data.", "Own one dimension of quality obsessively.", "Don’t dilute the core to chase every revenue idea early."],
    scenariosYes: ["Entering a ‘crowded’ category with a quality wedge", "Technical founders with a clear metric"],
    scenariosNo: ["Ignoring distribution forever"],
    resources: ["A measurable quality metric", "Technical depth", "Runway to prove the wedge"],
    takeaway: "Crowded markets still have room if you redefine the quality bar.",
    book: "In the Plex — Steven Levy",
    bookGain: "How Google’s culture, ranking obsession, and infrastructure scale emerged — and how focus on users (then advertisers) shaped the company."
  },
  {
    id: "zuckerberg", name: "Mark Zuckerberg", initials: "MZ", color: "#0866ff", category: "Technology",
    fail: "Early site crashes, exclusivity limits, copycat pressure", year: "2004–2006",
    story: "Thefacebook repeatedly struggled with scaling, competition from MySpace and others, and decisions about opening beyond campuses. Growth was chaotic and technically fragile before it stabilized.",
    whatTheyDid: "Moved fast on features users wanted. Expanded campus by campus. Prioritized growth and engagement metrics.",
    apply: ["Ship to a narrow beachhead first.", "Fix scale problems in parallel with growth, not after.", "Copycats force you to move faster on the real differentiator."],
    scenariosYes: ["Consumer social products", "Campus or community beachheads"],
    scenariosNo: ["Growth without any trust or safety basics"],
    resources: ["A tight initial network", "Engineering capacity for scaling", "Clear engagement metrics"],
    takeaway: "Early mess is normal; the discipline is choosing which fires to fight first.",
    book: "The Facebook Effect — David Kirkpatrick",
    bookGain: "The early growth playbook, culture of speed, and strategic choices that turned a campus site into a global network — including controversies that came with scale."
  },

  // ══════════ BUSINESS ══════════
  {
    id: "sanders", name: "Colonel Sanders", initials: "CS", color: "#ef4444", category: "Business",
    fail: "1,000+ recipe rejections", year: "1950s–60s",
    img: "Colonel_Sanders_in_character.jpg",
    story: "Harland Sanders perfected a fried-chicken recipe and method, then spent years pitching franchise deals. Rejected over a thousand times before the model stuck. KFC scaled when he was in his 60s and 70s.",
    whatTheyDid: "Turned a recipe into a franchise system. Kept pitching the same core product. Used his persona as the brand.",
    apply: ["If the product is strong, rejection is often about packaging or channel.", "Age is not a disqualifier; distribution is.", "Build a simple, repeatable system others can run."],
    scenariosYes: ["Franchise or license model", "Late-career product with proven demand"],
    scenariosNo: ["Pitching a weak product 1,000 times"],
    resources: ["A product people already like", "Outreach capacity", "Simple franchise docs"],
    takeaway: "Persistence only works if the underlying offer is good — then pitch volume matters.",
    book: "Colonel Sanders and the American Dream — Josh Ozersky",
    bookGain: "How a late-life franchise system and personal brand turned a regional recipe into a global chain — and the messier truths behind the myth."
  },
  {
    id: "ford", name: "Henry Ford", initials: "HF", color: "#64748b", category: "Business",
    fail: "Two failed automobile companies", year: "1899–1908",
    img: "Henry_ford_1919.jpg",
    story: "Ford’s early car companies failed. On the third attempt he focused on a simple, affordable car (Model T) and the moving assembly line, which changed manufacturing.",
    whatTheyDid: "Learned from production and capital failures. Bet on volume and affordability. Standardized parts and process.",
    apply: ["After two failures, change the strategy not just the logo.", "Ask: what would make this 10x more accessible?", "Process innovation can matter as much as product innovation."],
    scenariosYes: ["Hardware or manufacturing", "Market dominated by expensive incumbents"],
    scenariosNo: ["Ignoring capital structure after repeated bankruptcies"],
    resources: ["Engineering talent", "Patient manufacturing capital", "Willingness to standardize"],
    takeaway: "The third attempt often works when the first two taught process and positioning.",
    book: "My Life and Work — Henry Ford",
    bookGain: "Ford’s own account of production philosophy, wages, and simplicity — dated in places, still sharp on process and affordability as strategy."
  },
  {
    id: "dyson", name: "James Dyson", initials: "JD", color: "#06b6d4", category: "Business",
    fail: "5,126 failed prototypes", year: "1978–1993",
    img: "James_Dyson_at_the_Royal_Society.jpg",
    story: "Dyson spent 15 years and his savings building a bagless vacuum. Thousands of prototypes failed. Manufacturers refused to license it, so he manufactured it himself.",
    whatTheyDid: "Treated each prototype as an experiment. Refused to stop at good enough. Vertically integrated when partners said no.",
    apply: ["Log every prototype: what changed, what improved.", "If incumbents won’t license, consider making it yourself.", "Design can be a durable moat."],
    scenariosYes: ["Physical product with clear user pain", "Long R&D runway"],
    scenariosNo: ["Iterating without measuring user benefit", "Perfectionism that never ships"],
    resources: ["Workshop access", "Runway for years of iteration", "Manufacturing path"],
    takeaway: "High iteration count only pays off if each cycle teaches something measurable.",
    book: "Against the Odds — James Dyson",
    bookGain: "A masterclass in iterative engineering, IP fights, and building a manufacturer when the industry won’t partner. Motivating for hardware founders."
  },
  {
    id: "schultz", name: "Howard Schultz", initials: "HS", color: "#00704a", category: "Business",
    fail: "217 banks said no to Starbucks vision", year: "1980s",
    story: "Schultz wanted to expand Starbucks into a coffeehouse experience. Banks repeatedly rejected him. He eventually raised the money and scaled the café model globally.",
    whatTheyDid: "Sold a vision of experience, not just beans. Refined the pitch. Built store-level culture as the product.",
    apply: ["Track rejections and revise the one sentence that fails.", "Sell experience and culture, not only the commodity.", "One committed partner beats 200 lukewarm nos."],
    scenariosYes: ["Raising for a brand/experience business", "Turning a commodity into a ritual"],
    scenariosNo: ["Same pitch 217 times with no changes"],
    resources: ["A clear experience prototype (one store)", "Pitch materials that improve weekly"],
    takeaway: "Volume of nos is normal; improvement between nos is mandatory.",
    book: "Pour Your Heart Into It — Howard Schultz",
    bookGain: "How culture, store experience, and employee investment became Starbucks’ strategy — plus the messy growth years and comeback mindset."
  },
  {
    id: "knight", name: "Phil Knight", initials: "PK", color: "#111111", category: "Business",
    fail: "Nike started from a car trunk; constant cash stress", year: "1960s–70s",
    story: "Knight sold shoes from his car and lived with chronic cash shortages, customs issues, and factory risks. Blue Ribbon Sports became Nike through distribution and athlete relationships.",
    whatTheyDid: "Stayed close to athletes and retailers. Managed cash carefully. Built brand through performance and story.",
    apply: ["Start distribution before you have a perfect brand.", "Cash management is a core skill.", "Power-user relationships can replace big ad budgets early."],
    scenariosYes: ["Consumer product with passionate users", "Import/distribution business"],
    scenariosNo: ["Scaling inventory without cash controls"],
    resources: ["Samples and hustle", "Relationships with serious users", "Basic bookkeeping"],
    takeaway: "Many iconic brands looked like side hustles for a long time.",
    book: "Shoe Dog — Phil Knight",
    bookGain: "One of the best founder memoirs on cash crises, partnerships, and building a brand under pressure. Emotional and operational at once."
  },
  {
    id: "branson", name: "Richard Branson", initials: "RB", color: "#e10a0a", category: "Business",
    fail: "Multiple Virgin flops (Cola, Brides, Cars…)", year: "1980s–2000s",
    img: "Richard_Branson_2015.jpg",
    story: "Branson’s Virgin Group launched many ventures that failed or were sold at a loss. He treated them as experiments within a brand that could survive individual misses.",
    whatTheyDid: "Diversified bets under one brand. Exited failures without killing the core. Used publicity as a growth lever.",
    apply: ["Ring-fence experiments so one flop doesn’t sink the company.", "Learn which failures share a root cause.", "Brand equity can buy second chances — don’t waste it."],
    scenariosYes: ["Portfolio entrepreneurs", "Strong consumer brand entering new categories"],
    scenariosNo: ["Betting the core business on every experiment"],
    resources: ["A cash-generating core", "Clear kill criteria", "Public storytelling skill"],
    takeaway: "A brand that survives failure can afford more experiments — if you kill losers fast.",
    book: "Losing My Virginity — Richard Branson",
    bookGain: "How a publicity-driven, multi-industry empire is built — including the failures, near-bankruptcies, and personal risk behind the adventure brand."
  },
  {
    id: "hershey", name: "Milton Hershey", initials: "MH", color: "#a855f7", category: "Business",
    fail: "Two candy businesses failed", year: "1880s–1900s",
    img: "Milton_S._Hershey_c1915.jpg",
    story: "Hershey’s early candy ventures collapsed and left him nearly penniless. He later succeeded in caramel, sold that business, and built the chocolate company and model town that carry his name.",
    whatTheyDid: "Restarted with lessons from failed plants. Focused on a product he could scale. Reinvested in community and quality.",
    apply: ["Separate personal worth from one business failure.", "Carry process lessons, not just the product idea.", "When you win, decide what the wealth is for."],
    scenariosYes: ["Serial founders in manufacturing", "Rebuilding after bankruptcy"],
    scenariosNo: ["Repeating the same capital structure mistake"],
    resources: ["A craft you still believe in", "New capital or partners", "Willingness to relocate or restart"],
    takeaway: "Early bankruptcies can be chapters, not the whole book — if you change the method.",
    book: "Hershey: Milton S. Hershey’s Extraordinary Life of Wealth, Empire, and Utopian Dreams — Michael D’Antonio",
    bookGain: "How failure, caramel success, and chocolate scale intertwined with an unusual social vision for a company town."
  },
  {
    id: "huffington", name: "Arianna Huffington", initials: "AH", color: "#14b8a6", category: "Business",
    fail: "Book rejected 36 times", year: "1980s–2005",
    img: "Arianna_Huffington_2011_Shankbone_3.JPG",
    story: "After early success, Huffington faced a long string of publisher rejections. She later co-founded The Huffington Post and built a major digital media brand.",
    whatTheyDid: "Kept writing and public speaking. Moved into digital media when the format fit. Built a platform for many voices.",
    apply: ["Rejections in one medium don’t block another medium.", "Use a platform model when solo bylines stall.", "Timing matters as much as talent."],
    scenariosYes: ["Writers and media founders", "Pivoting from print to digital"],
    scenariosNo: ["Ignoring craft while chasing platform scale"],
    resources: ["A voice and network", "Willingness to change format", "Editorial partners"],
    takeaway: "A closed door in publishing can open a larger door in platforms.",
    book: "Thrive — Arianna Huffington",
    bookGain: "A reframe of success beyond money and status — sleep, well-being, and redefining the third metric. Useful after burnout or a hollow win."
  },
  {
    id: "kroc", name: "Ray Kroc", initials: "RK", color: "#fbbf24", category: "Business",
    fail: "Late-career salesman; many dry years", year: "1950s",
    story: "Kroc was a struggling milkshake-machine salesman in his 50s when he found the McDonald brothers’ efficient burger stand. He franchised and scaled the system into a global empire — not without bitter disputes.",
    whatTheyDid: "Recognized a system worth scaling. Obsessed over operations consistency. Pushed franchise growth aggressively.",
    apply: ["Look for systems, not just products.", "Ops discipline is a product.", "Late careers can still compound if you find the right vehicle."],
    scenariosYes: ["Franchise and ops-heavy businesses", "Mid-life career bets"],
    scenariosNo: ["Scaling without controlling quality"],
    resources: ["Eye for process", "Capital for expansion", "Franchise legal structure"],
    takeaway: "Sometimes the breakthrough is recognizing someone else’s system and industrializing it.",
    book: "Grinding It Out — Ray Kroc",
    bookGain: "How McDonald’s was scaled through obsession with process, franchising, and relentless sales energy — told by the man who did it."
  },

  // ══════════ LITERATURE ══════════
  {
    id: "rowling", name: "J.K. Rowling", initials: "JR", color: "#f43f5e", category: "Literature",
    fail: "Rejected by 12 publishers; living on benefits", year: "1995–97",
    img: "J._K._Rowling_2010.jpg",
    story: "As a single mother on welfare, Rowling finished Harry Potter and the Philosopher’s Stone. Twelve publishers rejected it. Bloomsbury took a chance; the series became a defining cultural franchise.",
    whatTheyDid: "Finished the manuscript despite conditions. Submitted repeatedly. Kept the voice consistent.",
    apply: ["Set a submission quota and track it.", "Separate ‘this isn’t for us’ from ‘this is bad’.", "Protect writing time even when life is unstable."],
    scenariosYes: ["Creative work facing gatekeepers", "Building something under financial stress"],
    scenariosNo: ["Never revising after clear craft feedback"],
    resources: ["A finished draft", "A tracking spreadsheet", "One trusted reader"],
    takeaway: "Gatekeepers are filters, not final judges — targeted submission volume matters.",
    book: "Harry Potter and the Philosopher’s Stone — J.K. Rowling",
    bookGain: "Immersion in the voice and world that survived the rejections — a reminder that the work itself is the point, not the query letter."
  },
  {
    id: "king", name: "Stephen King", initials: "SK", color: "#7c3aed", category: "Literature",
    fail: "Carrie rejected ~30 times; threw it away", year: "1973–74",
    img: "Stephen_King,_Comicon.jpg",
    story: "King collected rejection slips on a nail. He threw the Carrie draft away; his wife Tabitha retrieved it and urged him to finish. The novel launched his career.",
    whatTheyDid: "Kept writing short pieces for small payments. Accepted help when he had given up. Built output habits.",
    apply: ["Have one person allowed to rescue your drafts.", "Treat rejection slips as a progress metric.", "Ship short work while the long project matures."],
    scenariosYes: ["Novel stuck in self-doubt", "Building a body of work under rejection"],
    scenariosNo: ["Only writing when inspired"],
    resources: ["A trusted first reader", "A word-count rule", "Small paid outlets"],
    takeaway: "Sometimes the difference between quit and breakout is one person who refuses to let you throw it away.",
    book: "On Writing — Stephen King",
    bookGain: "The best practical memoir on craft and habit: toolbox, routine, cutting adverbs, and surviving both rejection and success."
  },
  {
    id: "seuss", name: "Dr. Seuss", initials: "DS", color: "#eab308", category: "Literature",
    fail: "First book rejected 27 times", year: "1937",
    img: "Ted_Geisel_NYWTS_2_crop.jpg",
    story: "And to Think That I Saw It on Mulberry Street was rejected by dozens of publishers. A chance sidewalk meeting with an editor led to publication.",
    whatTheyDid: "Stayed visible so luck could find him. Kept the distinctive style instead of flattening it.",
    apply: ["Stay visible in your industry while you collect rejections.", "Don’t sand off the weirdness that makes the work yours.", "One relationship can unlock closed doors."],
    scenariosYes: ["Creative work with an unusual voice"],
    scenariosNo: ["Waiting only for luck without submissions"],
    resources: ["A distinctive sample", "Industry weak ties", "Patience"],
    takeaway: "Persistence plus presence turns random luck into higher probability.",
    book: "Becoming Dr. Seuss — Brian Jay Jones",
    bookGain: "How Geisel’s voice, politics, and commercial path developed — useful for anyone protecting a strange, strong style."
  },
  {
    id: "grisham", name: "John Grisham", initials: "JG", color: "#0d9488", category: "Literature",
    fail: "First novel widely rejected", year: "1980s",
    img: "John_Grisham_2016.jpg",
    story: "A Time to Kill was rejected broadly. Grisham kept writing while practicing law; later legal thrillers sold in the tens of millions.",
    whatTheyDid: "Wrote in the margins of a demanding job. Stayed in a genre he knew from experience. Kept producing the next book.",
    apply: ["Use domain expertise as material.", "Don’t stop at book one if the craft is improving.", "A day job can fund the apprenticeship."],
    scenariosYes: ["Writing from professional experience", "Slow-burn second careers"],
    scenariosNo: ["Waiting for perfect conditions"],
    resources: ["Early-morning or late-night hours", "Industry knowledge", "Agent search persistence"],
    takeaway: "The second or third book often opens the door the first one couldn’t.",
    book: "A Time to Kill — John Grisham",
    bookGain: "See the raw early voice and legal-world texture that later commercial success polished — a baseline for genre writers."
  },
  {
    id: "christie", name: "Agatha Christie", initials: "AC", color: "#9f1239", category: "Literature",
    fail: "First novel rejected for years", year: "1916–1920",
    img: "Agatha_Christie.png",
    story: "The Mysterious Affair at Styles was turned down repeatedly before finding a publisher. Christie became the best-selling novelist of all time.",
    whatTheyDid: "Kept writing during and after WWI. Developed the puzzle-mystery form. Built series characters readers returned to.",
    apply: ["Series potential can matter as much as one plot.", "Genre mastery is a long game.", "Rejection delay is not the same as rejection forever."],
    scenariosYes: ["Mystery and genre fiction", "Building a long shelf of work"],
    scenariosNo: ["Abandoning a book after one no"],
    resources: ["A finished manuscript", "Familiarity with genre conventions", "Patience across years"],
    takeaway: "A slow start can still end as a dominant career in a category.",
    book: "An Autobiography — Agatha Christie",
    bookGain: "Christie’s own account of craft, travel, and persistence — quieter than the myths, rich on process and resilience."
  },
  {
    id: "potter", name: "Beatrix Potter", initials: "BP", color: "#65a30d", category: "Literature",
    fail: "Publishers rejected Peter Rabbit", year: "1901–1902",
    story: "Commercial publishers said no to The Tale of Peter Rabbit. Potter published it herself; it sold millions and defined a corner of children’s literature.",
    whatTheyDid: "Self-published when gatekeepers said no. Controlled the illustrations and tone. Expanded into a series and related products.",
    apply: ["Self-publishing is a valid path when quality is high.", "Own the visual and narrative voice together.", "A small print run can prove demand."],
    scenariosYes: ["Illustrated or niche children’s work", "Strong DIY capacity"],
    scenariosNo: ["Self-publishing with zero audience testing"],
    resources: ["Printing budget", "Illustration skill", "Direct sales channel"],
    takeaway: "Sometimes the market is wrong until you show them the book in hand.",
    book: "The Tale of Peter Rabbit — Beatrix Potter",
    bookGain: "A compact lesson in voice, illustration, and character — the artifact that gatekeepers missed."
  },
  {
    id: "angelou", name: "Maya Angelou", initials: "MA", color: "#be185d", category: "Literature",
    fail: "Years of hardship before I Know Why the Caged Bird Sings", year: "1960s–1969",
    img: "Maya_Angelou_2014.jpg",
    story: "Angelou survived trauma, silence, and instability before publishing the memoir that transformed American letters and her public life.",
    whatTheyDid: "Turned lived experience into crafted narrative. Kept working across performance and writing. Built a body of work over decades.",
    apply: ["Your hardest material can become your strongest work — with craft and care.", "Multiple art forms can feed each other.", "Timing of telling matters; so does survival until then."],
    scenariosYes: ["Memoir and personal narrative", "Artists rebuilding after trauma"],
    scenariosNo: ["Forcing publication before you’re safe enough to tell it"],
    resources: ["Support and safety", "Editorial partnership", "Time to shape the story"],
    takeaway: "Survival and craft together can turn private pain into public meaning.",
    book: "I Know Why the Caged Bird Sings — Maya Angelou",
    bookGain: "A foundational lesson in voice, honesty, and resilience — how narrative can reclaim agency."
  },

  // ══════════ SCIENCE ══════════
  {
    id: "edison", name: "Thomas Edison", initials: "TE", color: "#f97316", category: "Science",
    fail: "1,000+ light bulb attempts", year: "c. 1879",
    img: "Thomas_Edison2.jpg",
    story: "Edison’s lab tested filament after filament. He framed each failure as finding another way that did not work. The practical carbon-filament bulb changed daily life.",
    whatTheyDid: "Systematized experimentation. Logged results. Aimed at a commercial, durable product not just a lab demo.",
    apply: ["Design experiments so a no still teaches something.", "Optimize for a usable product, not a one-off prototype.", "Team labs beat lone genius myths."],
    scenariosYes: ["Hardware / materials R&D", "Large search-space problems"],
    scenariosNo: ["Random tinkering with no log"],
    resources: ["A test setup", "A results log", "A definition of done"],
    takeaway: "Failure count is only useful if each failure reduces the search space.",
    book: "Edison — Edmund Morris",
    bookGain: "A deep portrait of the inventor as operator: labs, patents, publicity, and the blurred line between genius and grind."
  },
  {
    id: "einstein", name: "Albert Einstein", initials: "AE", color: "#3b82f6", category: "Science",
    fail: "Labeled slow; struggled early academically", year: "late 1800s",
    img: "Einstein_1921_by_F_Schmutzer_-_restoration.jpg",
    story: "Einstein spoke late and was seen by some teachers as a poor student. He worked as a patent clerk while developing special relativity.",
    whatTheyDid: "Used a day job that left mental bandwidth. Thought in thought experiments. Published when ready, not when credentialed.",
    apply: ["A non-prestige job can fund deep work if it doesn’t exhaust you.", "Write and test ideas even without an academic post.", "Ignore early labels; track your own progress."],
    scenariosYes: ["Deep work alongside a survival job", "Fields that reward original thought"],
    scenariosNo: ["Romanticizing isolation with no feedback"],
    resources: ["Quiet time blocks", "Access to prior work", "At least one critical reader"],
    takeaway: "Early academic judgment is a weak predictor of original contribution.",
    book: "Einstein: His Life and Universe — Walter Isaacson",
    bookGain: "How curiosity, visualization, and stubborn independence produced relativity — and how fame complicated the man."
  },
  {
    id: "curie", name: "Marie Curie", initials: "MC", color: "#a21caf", category: "Science",
    fail: "Barred from proper labs; worked in a shed", year: "1890s–1900s",
    img: "Marie_Curie_c1920.jpg",
    story: "Facing gender barriers and limited resources, Curie conducted pioneering radioactivity research in poor conditions and won two Nobel Prizes in different sciences.",
    whatTheyDid: "Accepted constrained conditions without waiting for perfect facilities. Shared labor with a partner. Published rigorous results.",
    apply: ["Start with the lab you have.", "Partnership can multiply capacity under constraint.", "Let results argue for resources later."],
    scenariosYes: ["Research with limited funding", "Fields with structural bias"],
    scenariosNo: ["Ignoring safety in the name of hustle"],
    resources: ["Basic equipment", "A collaborator", "Discipline to document"],
    takeaway: "Constraints don’t forbid breakthroughs; they forbid excuses.",
    book: "Madame Curie — Eve Curie",
    bookGain: "An intimate account of scientific obsession under scarcity — partnership, grief, and standards that didn’t wait for permission."
  },
  {
    id: "tesla", name: "Nikola Tesla", initials: "NT", color: "#6366f1", category: "Science",
    fail: "Bankrupt; ideas ignored or taken", year: "1890s–1943",
    img: "Tesla_circa_1890.jpeg",
    story: "Tesla died nearly penniless. Many ideas were dismissed or under-monetized in his lifetime; later generations recognized their impact on AC power and more.",
    whatTheyDid: "Kept inventing despite financial chaos. Demonstrated technology dramatically. Struggled with business models and partnerships.",
    apply: ["Pair invention with a business partner who closes.", "Show, don’t only tell.", "IP and contracts matter as much as ideas."],
    scenariosYes: ["Deep tech inventors", "Public demonstration of new tech"],
    scenariosNo: ["Ignoring ownership and deals entirely"],
    resources: ["A commercial counterpart", "Demo capacity", "Legal basics on IP"],
    takeaway: "Brilliant ideas without a viable vehicle can still die poor — protect the path to market.",
    book: "Tesla: Inventor of the Electrical Age — W. Bernard Carlson",
    bookGain: "A grounded history of Tesla’s real achievements and limits — better than the myth, essential for inventors who need business realism."
  },
  {
    id: "darwin", name: "Charles Darwin", initials: "CD", color: "#84cc16", category: "Science",
    fail: "Delayed publishing for ~20 years", year: "1830s–1859",
    img: "Charles_Darwin_by_Julia_Margaret_Cameron,_c._1868.jpg",
    story: "Darwin held back Origin of Species out of fear, perfectionism, and care. When Wallace’s similar ideas pressed him, he published and rewrote biology.",
    whatTheyDid: "Accumulated evidence for decades. Corresponded widely. Published when priority and completeness forced the issue.",
    apply: ["Long research needs a ship date, not only more data.", "Peers can force healthy deadlines.", "Perfectionism can become avoidance."],
    scenariosYes: ["Big, paradigm-shifting work", "Evidence-heavy fields"],
    scenariosNo: ["Delaying forever without new evidence"],
    resources: ["A research log", "Trusted correspondents", "A commitment device to publish"],
    takeaway: "Depth is valuable until it becomes a hiding place — then ship.",
    book: "The Origin of Species — Charles Darwin",
    bookGain: "A primary text in careful argument from evidence — how to build a case that survives hostility."
  },
  {
    id: "goddard", name: "Robert Goddard", initials: "RG", color: "#10b981", category: "Science",
    fail: "Ridiculed for rocket ideas", year: "1920s",
    img: "Dr._Robert_H._Goddard_-_GPN-2000-001333.jpg",
    story: "The New York Times mocked the notion of spaceflight. Goddard kept experimenting largely out of the spotlight; later aerospace validated his direction.",
    whatTheyDid: "Continued private experiments. Patented key ideas. Avoided wasting all energy on public debate.",
    apply: ["When the press is wrong, the lab is still right — if the physics holds.", "Quiet progress can outlast ridicule.", "File patents and keep working."],
    scenariosYes: ["Contrarian technical work", "Long-horizon R&D"],
    scenariosNo: ["Ignoring all external critique including valid physics objections"],
    resources: ["Independent lab time", "Patent support", "Thick skin"],
    takeaway: "Ridicule is not peer review — but real peer review still matters.",
    book: "Rocket Man — David A. Clary",
    bookGain: "How Goddard worked through mockery and limited funding — a case study in long-horizon technical conviction."
  },

  // ══════════ SPORTS ══════════
  {
    id: "jordan", name: "Michael Jordan", initials: "MJ", color: "#dc2626", category: "Sports",
    fail: "Cut from high-school varsity team", year: "1978",
    img: "Michael_Jordan_in_2014.jpg",
    story: "As a sophomore Jordan was cut from the varsity team. He used the slight as fuel, trained obsessively, and became the defining basketball player of his era.",
    whatTheyDid: "Converted rejection into a training standard. Competed with himself daily. Improved weak parts of his game.",
    apply: ["Write down the rejection and the training response — make it specific.", "Improve the part of your game that got you cut.", "Use rivals as scheduled motivation, not identity."],
    scenariosYes: ["Cut from a team or program", "Skill fields where deliberate practice compounds"],
    scenariosNo: ["Obsession that burns you out"],
    resources: ["Practice time", "A coach or feedback source", "A measurable skill goal"],
    takeaway: "Rejection is useful when it becomes a training plan, not a personality.",
    book: "Driven from Within — Michael Jordan",
    bookGain: "Jordan’s own framing of standards, competitiveness, and mindset — motivational, best paired with a coach’s more critical view."
  },
  {
    id: "brady", name: "Tom Brady", initials: "TB", color: "#002244", category: "Sports",
    fail: "Drafted 199th overall", year: "2000",
    img: "Tom_Brady_2019.jpg",
    story: "Six quarterbacks were taken before Brady. He prepared like a starter, got his chance through injury, and built the most decorated QB career in NFL history.",
    whatTheyDid: "Prepared as if first string. Mastered the system. Stayed ready for a sudden window.",
    apply: ["When you’re not picked first, out-prepare the people who were.", "Learn the playbook deeper than anyone in your role.", "Windows open suddenly — readiness is the strategy."],
    scenariosYes: ["Backup or understudy roles", "Drafts and promotions that underranked you"],
    scenariosNo: ["Quiet quitting while waiting"],
    resources: ["Extra study time", "Relationship with coaches", "Skill maintenance"],
    takeaway: "Rankings measure the past; preparation measures the next opportunity.",
    book: "The TB12 Method — Tom Brady",
    bookGain: "Brady’s longevity and preparation philosophy — training, recovery, and treating the body as a long-term system."
  },
  {
    id: "phelps", name: "Michael Phelps", initials: "MP", color: "#1d4ed8", category: "Sports",
    fail: "ADHD; told he would never focus", year: "1990s–2016",
    img: "Michael_Phelps_Rio_Olympics_2016.jpg",
    story: "Phelps struggled in school and with attention. He channelled energy into swimming and became the most decorated Olympian ever — while also facing mental health battles later.",
    whatTheyDid: "Found a channel for intensity. Worked with a coach who structured volume. Later spoke openly about mental health.",
    apply: ["Match the environment to the brain you have.", "Structure and coaching can outperform willpower alone.", "Success doesn’t cancel the need for mental health care."],
    scenariosYes: ["High-energy people in the wrong environment", "Athletes and performers under pressure"],
    scenariosNo: ["Using achievement to avoid treating mental health"],
    resources: ["A structured training environment", "Coaching", "Mental health support"],
    takeaway: "The trait that looks like a problem in one system can be an edge in another — and still needs care.",
    book: "No Limits — Michael Phelps",
    bookGain: "Training volume, goal-setting, and the psychological cost of greatness from the most decorated Olympian."
  },
  {
    id: "serena", name: "Serena Williams", initials: "SW", color: "#7c2d12", category: "Sports",
    fail: "Early losses and ranking doubts", year: "1990s–2010s",
    img: "Serena_Williams_at_2013_US_Open.jpg",
    story: "Serena faced ranking skepticism and tough early losses. She went on to win 23 Grand Slam singles titles and reshape women’s tennis.",
    whatTheyDid: "Trained with family systems that demanded excellence. Improved constantly. Used doubt as fuel without letting it define her.",
    apply: ["Build a training environment that expects more than the rankings do.", "Long careers have many ‘early’ chapters.", "Excellence can be a response to being underestimated."],
    scenariosYes: ["Athletes and professionals counted out early", "Family or small-team training systems"],
    scenariosNo: ["Ignoring injury and recovery"],
    resources: ["High-standard practice partners", "Long-term development plan", "Support system"],
    takeaway: "Rankings lag talent — keep developing until the results catch up.",
    book: "My Life: Queen of the Court — Serena Williams",
    bookGain: "Serena’s path through doubt, dominance, and identity — useful for anyone building excellence under scrutiny."
  },
  {
    id: "ruth", name: "Babe Ruth", initials: "BR", color: "#b45309", category: "Sports",
    fail: "Career strikeout record alongside home runs", year: "1910s–30s",
    img: "Babe_Ruth2.jpg",
    story: "Ruth held the strikeout record for decades while rewriting the home-run books. Failure and dominance were built into the same aggressive swing.",
    whatTheyDid: "Accepted strikeouts as the cost of power. Changed baseball’s offensive philosophy. Stayed aggressive.",
    apply: ["Some strategies raise both ceiling and failure rate — own that tradeoff.", "Don’t optimize only for looking safe.", "Public failure is tolerable if the upside is transformative."],
    scenariosYes: ["High-upside creative or sales work", "Roles where variance is the point"],
    scenariosNo: ["Ignoring process when swing rate is high"],
    resources: ["A role that tolerates variance", "Metrics that capture upside not only error rate"],
    takeaway: "The same approach can produce both the outs and the legends — judge the portfolio, not one at-bat.",
    book: "The Big Fella — Jane Leavy",
    bookGain: "Ruth as athlete and cultural force — how power, appetite, and myth reshaped the game."
  },

  // ══════════ ENTERTAINMENT ══════════
  {
    id: "disney", name: "Walt Disney", initials: "WD", color: "#2563eb", category: "Entertainment",
    fail: "Fired for lacking imagination; early bankruptcies", year: "1920s–30s",
    img: "Walt_Disney_1946.JPG",
    story: "A newspaper editor said Disney lacked imagination. His early studio went bankrupt. He rebuilt around characters he controlled and quality standards that created an empire.",
    whatTheyDid: "Owned the IP when possible. Reinvested in craft. Turned setbacks into studio standards.",
    apply: ["Don’t outsource ownership of your core ideas.", "Use early failure as a quality bar.", "Story clarity beats technical novelty alone."],
    scenariosYes: ["Creative business with IP", "Rebuilding after a failed studio"],
    scenariosNo: ["Ignoring business fundamentals while chasing art"],
    resources: ["Control of key IP", "A team that shares standards", "Willingness to restart"],
    takeaway: "Imagination critiques are often about fit, not capacity — change the venue, not your core.",
    book: "Walt Disney: The Triumph of the American Imagination — Neal Gabler",
    bookGain: "The definitive long view of Disney’s ambition, failures, and control of story — how a studio culture is built."
  },
  {
    id: "spielberg", name: "Steven Spielberg", initials: "SS", color: "#9333ea", category: "Entertainment",
    fail: "Rejected by USC film school", year: "1960s–70s",
    img: "Steven_Spielberg_by_Gage_Skidmore.jpg",
    story: "Spielberg was rejected by USC’s film program multiple times. He learned by making films, got onto studio lots, and directed Jaws — then became a defining force in cinema.",
    whatTheyDid: "Made films instead of waiting for permission. Networked onto lots. Delivered under pressure when the chance came.",
    apply: ["Build a portfolio while institutions say no.", "Proximity to the industry can substitute for a credential.", "Be ready to execute when the window opens."],
    scenariosYes: ["Creative fields with elite schools", "Apprenticeship-by-doing paths"],
    scenariosNo: ["Networking without any work to show"],
    resources: ["A reel or body of work", "Access to sets or collaborators", "Relentless output"],
    takeaway: "Credentials are one path; finished work and proximity are another.",
    book: "Steven Spielberg: A Biography — Joseph McBride",
    bookGain: "How craft, ambition, and studio politics shaped a career that institutions initially blocked."
  },
  {
    id: "oprah", name: "Oprah Winfrey", initials: "OW", color: "#c026d3", category: "Entertainment",
    fail: "Fired from her first TV job", year: "early 1980s",
    img: "Oprah_in_2014.jpg",
    story: "Fired from a Baltimore news role and told she was unfit for television. She shifted toward a more authentic on-air style and built one of the most influential media careers of the era.",
    whatTheyDid: "Stopped imitating traditional anchors. Leaned into conversation and empathy. Built audience trust over time.",
    apply: ["If a format rejects you, change the format not your personality.", "Audience trust compounds slower than hype but lasts longer.", "Turn a firing into a positioning decision."],
    scenariosYes: ["Media and public-facing roles", "Being ‘too much’ or ‘not enough’ for a template"],
    scenariosNo: ["Ignoring craft while relying only on authenticity"],
    resources: ["A platform even if small", "Audience feedback", "Time to iterate on-air"],
    takeaway: "Fit matters more than generic talent — find the format that fits you.",
    book: "What I Know For Sure — Oprah Winfrey",
    bookGain: "Short, reflective lessons on resilience, intention, and self-definition — accessible after a public or private setback."
  },
  {
    id: "beatles", name: "The Beatles", initials: "TB", color: "#1e3a5f", category: "Entertainment",
    fail: "Rejected by Decca Records", year: "1962",
    img: "The_Beatles_arrive_at_JFK_Airport.jpg",
    story: "Decca passed, suggesting guitar groups were on the way out. They signed with EMI, worked intensely in Hamburg and the studio, and reshaped popular music.",
    whatTheyDid: "Kept performing and tightening the act. Found a producer and label that got them. Wrote constantly.",
    apply: ["One gatekeeper is not the market.", "Live reps improve the product faster than waiting for a deal.", "Chemistry with the right partner beats a prestigious wrong partner."],
    scenariosYes: ["Bands, startups, creators seeking a platform deal"],
    scenariosNo: ["Blaming one rejection for quitting the craft"],
    resources: ["Stage time", "A growing catalog", "A champion inside a system"],
    takeaway: "Historic nos are often about the listener, not the music.",
    book: "Tune In — Mark Lewisohn",
    bookGain: "Exhaustive early Beatles history — how grind, chemistry, and the right allies turned a rejected band into a cultural pivot."
  },
  {
    id: "ball", name: "Lucille Ball", initials: "LB", color: "#e11d48", category: "Entertainment",
    fail: "Told she had no future in comedy", year: "1930s–1950s",
    img: "Lucille_Ball_1950s.png",
    story: "Ball’s early career was rocky and she was told comedy wasn’t her future. I Love Lucy made her a legend and a pioneering TV executive.",
    whatTheyDid: "Found the format (sitcom + physical comedy + real marriage chemistry) that fit. Took ownership stakes. Built a production empire.",
    apply: ["Wrong genre advice can be about the market’s imagination, not your talent.", "Ownership of the show matters.", "Partnership on-screen and off can be the product."],
    scenariosYes: ["Performers miscast early", "Creators who want ownership"],
    scenariosNo: ["Ignoring audience testing entirely"],
    resources: ["A format experiment", "A strong partner", "Business advice on ownership"],
    takeaway: "The industry can be wrong about your genre — prove it with the right vehicle.",
    book: "Ball of Fire — Stefan Kanfer",
    bookGain: "How Ball fought for creative control and built Desilu — comedy, power, and business in early TV."
  },
  {
    id: "poitier", name: "Sidney Poitier", initials: "SP", color: "#1e40af", category: "Entertainment",
    fail: "Told to become a dishwasher", year: "1940s–1963",
    img: "Sidney_Poitier_1963.jpg",
    story: "A casting director told Poitier to forget acting. He became the first Black man to win the Best Actor Oscar and opened doors across Hollywood.",
    whatTheyDid: "Trained obsessively in speech and craft. Chose roles with care. Used success to expand opportunity for others.",
    apply: ["Treat dismissive gatekeepers as data about them, not destiny.", "Craft can overcome accent, origin, and prejudice — not alone, but it matters.", "Success can be leveraged for the next generation."],
    scenariosYes: ["Breaking into closed industries", "Underestimated performers"],
    scenariosNo: ["Enduring abuse with no boundary or exit"],
    resources: ["Training", "Allies inside the system", "Role selectivity"],
    takeaway: "A single cruel verdict is not the industry’s final word — but you still need craft and allies.",
    book: "The Measure of a Man — Sidney Poitier",
    bookGain: "Poitier’s reflections on dignity, craft, and navigating a hostile industry — quiet strength as strategy."
  },
  {
    id: "astaire", name: "Fred Astaire", initials: "FA", color: "#d946ef", category: "Entertainment",
    fail: "‘Can’t act. Slightly bald. Can dance a little.’", year: "1930s",
    img: "Fred_Astaire_in_Royal_Wedding_2.jpg",
    story: "The (maybe apocryphal) screen-test note became legend. Astaire became one of the most elegant dancers and screen partners in film history.",
    whatTheyDid: "Obsessed over rehearsal and camera-friendly choreography. Partnered brilliantly. Made effort look effortless.",
    apply: ["Early evaluations can miss the dimension you actually dominate.", "Rehearsal is the product.", "Partnership multiplies talent."],
    scenariosYes: ["Performers with mixed early feedback", "Crafts where polish is everything"],
    scenariosNo: ["Ignoring the parts of the note that are true"],
    resources: ["Rehearsal time", "The right partner", "Camera or stage practice"],
    takeaway: "A dismissive note can become a joke you outlive — if the work is undeniable.",
    book: "Steps in Time — Fred Astaire",
    bookGain: "Astaire’s own account of discipline and partnership — how ‘effortless’ is manufactured."
  },

  // ══════════ POLITICS & FASHION ══════════
  {
    id: "lincoln", name: "Abraham Lincoln", initials: "AL", color: "#475569", category: "Politics & Fashion",
    fail: "Lost elections; failed businesses; deep personal loss", year: "1830s–1860",
    img: "Abraham_Lincoln_O-77_matte_collodion_print.jpg",
    story: "Lincoln failed in business, lost multiple races, and endured profound grief. He continued in law and politics, won the presidency in 1860, and led through the Civil War.",
    whatTheyDid: "Stayed in public life despite losses. Built a reputation for honesty and argument. Learned from each campaign.",
    apply: ["Treat each loss as a retrospective.", "Character reputation is a long-term asset.", "Keep a day craft that funds the longer fight."],
    scenariosYes: ["Electoral or organizational politics", "Long-horizon leadership under setbacks"],
    scenariosNo: ["Ignoring personal health while romanticizing struggle"],
    resources: ["A supporting livelihood", "Allies", "Recovery practices after loss"],
    takeaway: "Failure can coexist with eventual consequential leadership — if you stay in the arena.",
    book: "Team of Rivals — Doris Kearns Goodwin",
    bookGain: "How Lincoln turned rivals into a cabinet and led through crisis — empathy and political skill as tools, not soft extras."
  },
  {
    id: "churchill", name: "Winston Churchill", initials: "WC", color: "#1e293b", category: "Politics & Fashion",
    fail: "Years in the political wilderness", year: "1930s–1940",
    img: "Winston_Churchill_1945.jpg",
    story: "Churchill spent much of the 1930s out of power, often dismissed. When crisis arrived he was asked to lead and became central to WWII leadership and rhetoric.",
    whatTheyDid: "Kept writing and speaking. Maintained a network. Prepared intellectually for the crisis he expected.",
    apply: ["Use exile to write, study, and stay ready.", "Being early can look like being wrong — until it doesn’t.", "Crisis promotes the prepared, not only the popular."],
    scenariosYes: ["Sidelines after a career setback", "Warning about risks others ignore"],
    scenariosNo: ["Isolation without any platform"],
    resources: ["A writing or speaking channel", "Strategic study", "Health enough to return"],
    takeaway: "Wilderness years are wasted only if you stop preparing.",
    book: "The Splendid and the Vile — Erik Larson",
    bookGain: "Churchill’s leadership under the Blitz in human detail — rhetoric, routine, and household under fire."
  },
  {
    id: "wang", name: "Vera Wang", initials: "VW", color: "#db2777", category: "Politics & Fashion",
    fail: "Missed Olympic figure-skating team", year: "1960s–80s",
    img: "Vera_Wang.jpg",
    story: "Wang’s Olympic skating ambition ended. She moved into fashion editorial and then design, becoming one of the most influential bridal designers.",
    whatTheyDid: "Transferred discipline from sport to craft. Learned inside the industry before launching. Focused on a clear high-emotion niche.",
    apply: ["Skills from a failed primary dream often transfer.", "Work inside the industry before betting on your name.", "Niche + emotion + craft can beat broad mediocrity."],
    scenariosYes: ["Career change after a closed athletic path", "Luxury or craft brands"],
    scenariosNo: ["Abandoning all discipline from the old field"],
    resources: ["Apprenticeship access", "A sharp niche", "Standards from high-performance training"],
    takeaway: "A closed door in one arena can be training for mastery in another.",
    book: "Vera Wang (profiles) / The Fashion Business Manual — Fashionary",
    bookGain: "For Wang’s path, long-form profiles capture the pivot; a fashion business manual adds practical brand-building structure for designers."
  },
  {
    id: "chanel", name: "Coco Chanel", initials: "CC", color: "#18181b", category: "Politics & Fashion",
    fail: "Orphanage childhood; early commercial struggles", year: "1900s–1920s",
    img: "Coco_Chanel_1931.jpg",
    story: "Raised in an orphanage, Chanel began with hats and small efforts that struggled. She built a style around simplicity and liberation from restrictive fashion.",
    whatTheyDid: "Designed for how women wanted to move. Built a coherent taste system. Turned constraint into aesthetic clarity.",
    apply: ["Design for real use, not only display.", "A strong point of view beats trend-chasing.", "Origin can inform product principles."],
    scenariosYes: ["Product design and fashion", "Brands built on a clear philosophy"],
    scenariosNo: ["Copying aesthetics without the use-case"],
    resources: ["Craft skill", "A distinct taste thesis", "Early customers who live the lifestyle"],
    takeaway: "Constraint can produce clarity — if you design from real life.",
    book: "Coco Chanel: The Legend and the Life — Justine Picardie",
    bookGain: "Chanel’s invention of modern ease in dress — and the complicated person behind the brand mythology."
  },
  {
    id: "obama", name: "Barack Obama", initials: "BO", color: "#1e3a8a", category: "Politics & Fashion",
    fail: "Lost first congressional primary (2000)", year: "2000",
    story: "Obama lost a congressional primary badly. He regrouped, refined his approach, and later won the U.S. Senate and the presidency.",
    whatTheyDid: "Analyzed the loss. Built broader coalitions. Wrote and spoke to clarify the message. Ran again at a different level with better organization.",
    apply: ["A blowout loss can be diagnostic if you study it.", "Message and organization both matter.", "Don’t only re-run the same race — change the map."],
    scenariosYes: ["Political and organizational campaigns", "Public leadership after a visible loss"],
    scenariosNo: ["Repeating the same coalition math that failed"],
    resources: ["A post-mortem", "Writers and organizers", "Time before the next race"],
    takeaway: "A decisive loss can be the best data you’ll get — if you use it.",
    book: "A Promised Land — Barack Obama",
    bookGain: "Obama’s own account of decision-making, campaigning, and the weight of office — including the long road after early defeat."
  },
  {
    id: "mandela", name: "Nelson Mandela", initials: "NM", color: "#166534", category: "Politics & Fashion",
    fail: "27 years in prison", year: "1962–1990",
    story: "Mandela was imprisoned for 27 years for opposing apartheid. He emerged to negotiate a transition and become South Africa’s first Black president.",
    whatTheyDid: "Maintained political discipline in prison. Built relationships even with adversaries. Chose reconciliation as strategy, not only idealism.",
    apply: ["Long confinement or exclusion can still be used to prepare.", "Reconciliation can be a power move, not a soft one.", "Personal dignity under oppression is a form of leadership."],
    scenariosYes: ["Long struggles against unjust systems", "Negotiating after conflict"],
    scenariosNo: ["Romanticizing suffering without a political strategy"],
    resources: ["Inner discipline", "Allies outside", "A negotiation theory of change"],
    takeaway: "Time taken from you can still be shaped into preparation — if you refuse to surrender the inner project.",
    book: "Long Walk to Freedom — Nelson Mandela",
    bookGain: "How endurance, negotiation, and moral clarity coexisted across decades — a primary text on patient power."
  }
];
