/* Compact mega catalog — expands on load */
(function(){
var C=["Technology","Business","Literature","Science","Sports","Entertainment","Politics & Fashion"];
var R=[
["ellison","Larry Ellison",0,"Oracle near-bankrupt twice","1970s-90s","Early software ventures almost died before database dominance."],
["ballmer","Steve Ballmer",0,"Missed mobile","2000s","Windows Phone failed despite Microsoft resources."],
["andreessen","Marc Andreessen",0,"Netscape lost browser war","1990s","Microsoft bundling crushed the pioneer browser."],
["yang","Jerry Yang",0,"Yahoo decline as CEO","2007-09","Search and media position eroded."],
["mayer","Marissa Mayer",0,"Yahoo turnaround failed","2012-17","Acquisitions did not reverse decline."],
["nadella","Satya Nadella",0,"Long path before cloud bet","1990s-2010s","Mobile miss was backdrop for cloud pivot."],
["cook","Tim Cook",0,"Post-Jobs skepticism","2011","Markets doubted a non-product CEO."],
["woz","Steve Wozniak",0,"US Festival losses","1980s","Costly festival; left Apple ops."],
["torvalds","Linus Torvalds",0,"Linux scoffed at","1990s","Hobby kernel dismissed by vendors."],
["tbl","Tim Berners-Lee",0,"WWW ignored at CERN","1989-93","Hypertext proposal got limited support."],
["bricklin","Dan Bricklin",0,"VisiCalc lost to Lotus","1980s","Invented spreadsheet, missed platform rents."],
["hastings","Reed Hastings",0,"Pure Software chaos","1990s","Painful management years before Netflix."],
["benioff","Marc Benioff",0,"Salesforce called a toy","2000s","Enterprise mocked cloud CRM."],
["butterfield","Stewart Butterfield",0,"Game failed → Slack","2000s","Glitch pivot to workplace chat."],
["dorsey","Jack Dorsey",0,"Ousted from Twitter","2008","CEO exile then return."],
["systrom","Kevin Systrom",0,"Burbn too broad","2010","Stripped to photos = Instagram."],
["houston","Drew Houston",0,"USB forgot; storage skepticism","2007","Demo video proved Dropbox demand."],
["acton","Brian Acton",0,"Yahoo rejection","2009","WhatsApp after being turned away."],
["koum","Jan Koum",0,"Welfare childhood","1990s","Immigrant poverty before WhatsApp."],
["ek","Daniel Ek",0,"Music industry hostility","2006","Spotify licensing wars."],
["parker","Sean Parker",0,"Napster shut down","2001","Legal assault ended first act."],
["fanning","Shawn Fanning",0,"Napster destruction","2001","Founder at center of shutdown."],
["walton","Sam Walton",0,"Franchise limits","1940s-60s","Built Walmart his own way."],
["buffett","Warren Buffett",1,"Textile drag; early nos","1950s-80s","Berkshire shell from dying mills."],
["munger","Charlie Munger",1,"Early losses; divorce","1950s","Personal setbacks before Buffett."],
["graham","Benjamin Graham",1,"1929 near wipeout","1929","Value rules born from crash."],
["dalio","Ray Dalio",1,"1982 wrong call; broke","1982","Firm nearly failed after macro miss."],
["burry","Michael Burry",1,"Ridiculed for housing short","2005-08","Partners fought the subprime bet."],
["blank","Steve Blank",1,"Failed startups","1980s-90s","Customer development from failure."],
["ries","Eric Ries",1,"IMVU painful pivots","2000s","MVP discipline from game pivots."],
["pg","Paul Graham",1,"Viaweb stress","1990s","Hard years before YC."],
["lütke","Tobi Lütke",1,"Snowdevil almost stayed a shop","2004","Shopify from a snowboard store need."],
["blakely2","Sara Blakely",1,"Mills rejected Spanx","1990s","Door-to-door fax sales while prototyping."],
["walker2","Madam C.J. Walker",1,"Poverty; widowhood","1900s","Door-to-door to hair-care empire."],
["lauder2","Estée Lauder",1,"Buyer rejections","1940s","Samples and counter presence."],
["knight2","Phil Knight",1,"Cash crises","1960s-70s","Shoe Dog trunk years."],
["schultz2","Howard Schultz",1,"217 bank nos","1980s","Starbucks vision rejected."],
["branson2","Richard Branson",1,"Virgin flops","1980s-2000s","Cola, Brides, Cars failed."],
["kamprad","Ingvar Kamprad",1,"Early bans; past shame","1950s","IKEA flat-pack under stigma."],
["chouinard","Yvon Chouinard",1,"Near-broke climber","1960s","Patagonia from dirtbag years."],
["marykay","Mary Kay Ash",1,"Passed over for male mentee","1960s","Direct sales empire after slight."],
["melville","Herman Melville",2,"Moby-Dick flopped","1851","Died obscure as customs inspector."],
["poe","Edgar Allan Poe",2,"Poverty; fired","1830s-49","Chronic money failure."],
["dickinson","Emily Dickinson",2,"Almost unpublished","1800s","Unknown while alive."],
["kafka","Franz Kafka",2,"Ordered works burned","1924","Friend saved the manuscripts."],
["woolf","Virginia Woolf",2,"Rejection; illness","1900s-41","Publishing and health battles."],
["joyce","James Joyce",2,"Ulysses banned","1920s","Censorship and poverty."],
["faulkner","William Faulkner",2,"Hollywood hack work","1930s","Studio years to pay bills."],
["fitzgerald","F. Scott Fitzgerald",2,"Considered washed up","1930s","Gatsby rose posthumously."],
["lee_harper","Harper Lee",2,"One novel for decades","1960s","Pressure after Mockingbird."],
["plath","Sylvia Plath",2,"Rejection slips","1950s","Bell Jar under pseudonym."],
["baldwin","James Baldwin",2,"Exile; hostility","1940s-60s","Paris then US fire."],
["hurston","Zora Neale Hurston",2,"Died poor; out of print","1950s","Revival decades later."],
["austen","Jane Austen",2,"Long path to print","1790s-1810s","Quiet persistence."],
["tolkien","J.R.R. Tolkien",2,"LOTR long delay","1930s-50s","Academic day job."],
["orwell2","George Orwell",2,"Early poverty","1920s-30s","Down and Out years."],
["morrison2","Toni Morrison",2,"Wrote before dawn","1960s-70s","Editor and single mother."],
["solzhenitsyn","Aleksandr Solzhenitsyn",2,"Gulag; banned","1940s-70s","Archive of the camps."],
["rushdie","Salman Rushdie",2,"Fatwa exile","1989","Life under threat."],
["newton","Isaac Newton",3,"Plague isolation; feuds","1660s","Principia despite politics."],
["galileo","Galileo",3,"Inquisition; house arrest","1633","Forced recantation."],
["mendel","Gregor Mendel",3,"Work ignored 35 years","1866-1900","Genetics rediscovered later."],
["semmelweis","Ignaz Semmelweis",3,"Ridiculed for handwashing","1840s","Died without acceptance."],
["wegener","Alfred Wegener",3,"Drift theory rejected","1912-30s","Plate tectonics vindicated."],
["mcclintock","Barbara McClintock",3,"Jumping genes ignored","1940s-80s","Nobel after solitude."],
["goodall","Jane Goodall",3,"Uncredentialed critique","1960s","Field methods attacked."],
["carson","Rachel Carson",3,"Industry attacks","1962","Silent Spring under fire."],
["turing","Alan Turing",3,"Prosecuted; dead at 41","1952-54","State destroyed him."],
["lovelace","Ada Lovelace",3,"Engine unfinished","1840s","Vision beyond machines."],
["hopper","Grace Hopper",3,"Navy and COBOL skepticism","1940s-60s","Compilers as infrastructure."],
["hamilton","Margaret Hamilton",3,"Software not serious","1960s","Apollo code under deadline."],
["johnson_k","Katherine Johnson",3,"Segregated computers","1950s-60s","Hidden Figures math."],
["kariko","Katalin Karikó",3,"Demoted; mRNA dismissed","1990s-2010s","Vaccine foundation after exile."],
["franklin2","Rosalind Franklin",3,"Photo 51 credit delay","1950s","DNA structure politics."],
["hawking2","Stephen Hawking",3,"ALS; years to live","1963","Decades of theory after diagnosis."],
["wright_bros","Wright Brothers",3,"Press ridicule","1903","Bike shop methodical tests."],
["goddard3","Robert Goddard",3,"NYT rocket mockery","1920","Private experimentation."],
["tesla2","Nikola Tesla",3,"Bankrupt; ignored","1890s-1943","Died nearly penniless."],
["curie3","Marie Curie",3,"Shed lab; sexism","1890s","Two Nobels under constraint."],
["jordan3","Michael Jordan",4,"Cut from varsity","1978","Fuel for greatness."],
["brady3","Tom Brady",4,"199th pick","2000","Most decorated QB."],
["ali4","Muhammad Ali",4,"Stripped of title","1967-70","Banned for draft refusal."],
["biles3","Simone Biles",4,"Twisties withdrawal","2021","Mental health as performance."],
["tiger3","Tiger Woods",4,"Scandal and injury","2009-14","2019 Masters return."],
["owens","Jesse Owens",4,"US racism after Olympics","1936","Four golds then limited opportunity."],
["robinson","Jackie Robinson",4,"Abuse breaking color line","1947","Daily attacks."],
["kaepernick","Colin Kaepernick",4,"Kneel; no team","2016","Protest cost a career."],
["magic","Magic Johnson",4,"HIV diagnosis","1991","Life after the announcement."],
["curry","Stephen Curry",4,"Too small; ankles","2009","Revolution from deep."],
["lebron","LeBron James",4,"Decision backlash","2010","Titles after the hate."],
["serena4","Serena Williams",4,"Ranking doubts","1990s","23 majors."],
["osaka","Naomi Osaka",4,"Media room pressure","2021","Mental health pause."],
["federer2","Roger Federer",4,"Early temper; exits","1990s","Calm peak years."],
["nadal","Rafael Nadal",4,"Chronic foot pain","2000s","Clay under injury."],
["bolt2","Usain Bolt",4,"Scoliosis; false starts","2000s","9.58 after pressure."],
["phelps3","Michael Phelps",4,"ADHD; depression","1990s-2016","Most decorated Olympian."],
["messi2","Lionel Messi",4,"Growth hormone need","1990s","Medical support to continue."],
["ronaldo2","Cristiano Ronaldo",4,"Homesick teen at United","2003","Training obsession."],
["chaplin","Charlie Chaplin",5,"Exiled from US","1950s","McCarthy-era ban."],
["welles","Orson Welles",5,"Studio exile after Kane","1941","Lost control after masterpiece."],
["kubrick2","Stanley Kubrick",5,"Studio fights","1950s","Autonomy model."],
["scorsese2","Martin Scorsese",5,"Flops; cocaine years","1970s-80s","Raging Bull reset."],
["coppola2","Francis Ford Coppola",5,"One from the Heart bankruptcy","1982","Zoetrope near collapse."],
["lucas2","George Lucas",5,"Star Wars doubted","1977","Studios did not understand."],
["tarantino2","Quentin Tarantino",5,"Video store years","1980s","Long unproduced scripts."],
["lee_spike","Spike Lee",5,"Maxed credit cards","1980s","First feature self-funded."],
["miyazaki2","Hayao Miyazaki",5,"Ghibli near collapse","1980s-90s","Financial brink."],
["kuro","Akira Kurosawa",5,"Suicide attempt","1970s","After commercial failure."],
["poitier2","Sidney Poitier",5,"Told to wash dishes","1940s","First Black Best Actor."],
["freeman","Morgan Freeman",5,"Broke until 50","1980s","Late leading man."],
["carey","Jim Carrey",5,"Homeless stretch","1980s","In Living Color leap."],
["carell","Steve Carell",5,"Late Office break","2000s","40-year-old virgin path."],
["williams_r","Robin Williams",5,"Depression under comedy","1990s-2014","Genres beyond stand-up."],
["pryor2","Richard Pryor",5,"Freebase incident","1980","Career nearly ended."],
["gaga3","Lady Gaga",5,"Dropped by Def Jam","2006","Nightlife rebuild."],
["swift3","Taylor Swift",5,"Masters dispute","2019","Re-recording strategy."],
["beyonce3","Beyoncé",5,"Destiny’s Child drama","2000-03","Solo control."],
["jayz","Jay-Z",5,"Drug years; shelved album","1990s","Empire after street."],
["eminem","Eminem",5,"Poverty; addiction","1990s-2000s","Relapse recovery."],
["hendrix2","Jimi Hendrix",5,"US ignored him","1960s","London breakthrough."],
["cobain2","Kurt Cobain",5,"Fame aversion","1990s","Unwanted superstardom."],
["winehouse","Amy Winehouse",5,"Addiction spectacle","2000s","Back to Black peak."],
["turner","Tina Turner",5,"Abuse by Ike","1970s","Private Dancer rebirth."],
["presley","Elvis Presley",5,"Hollywood mediocrity","1960s","68 Comeback Special."],
["dylan2","Bob Dylan",5,"Electric boos","1965","Folk audience revolt."],
["bowie","David Bowie",5,"Years of flops","1960s","Reinvention doctrine."],
["prince3","Prince",5,"Warner name war","1990s","Ownership insistence."],
["churchill3","Winston Churchill",6,"Gallipoli disaster","1915","Wilderness then WWII."],
["lincoln3","Abraham Lincoln",6,"Lost elections; depression","1830s-60s","Team of Rivals."],
["grant2","Ulysses S. Grant",6,"Failed business; drinking","1850s","War command after failure."],
["truman2","Harry Truman",6,"Haberdashery bankruptcy","1920s","Failed business before politics."],
["nixon2","Richard Nixon",6,"1960 loss; resignation","1960-74","Comeback then self-destruction."],
["carter2","Jimmy Carter",6,"1980 landslide loss","1980","Model post-presidency."],
["mandela3","Nelson Mandela",6,"27 years prison","1962-90","Negotiation from a cell."],
["ghandi3","Mahatma Gandhi",6,"Train ejection","1890s","Method from humiliation."],
["mlk","Martin Luther King Jr.",6,"Jailed; house bombed","1950s-60s","Nonviolence under terror."],
["malcolm","Malcolm X",6,"Criminal youth; NOI split","1940s-65","Reinvention then assassination."],
["fdr2","Franklin D. Roosevelt",6,"Polio; career seemed over","1921","Redesigned public operation."],
["eleanor2","Eleanor Roosevelt",6,"Painful marriage; shyness","1900s","Human rights platform."],
["obama3","Barack Obama",6,"Lost 2000 primary","2000","Blowout loss then rise."],
["chanel2","Coco Chanel",6,"Orphanage; wartime stigma","1900s","Modern silhouette."],
["ysl","Yves Saint Laurent",6,"Fired from Dior; breakdowns","1960s","Ready-to-wear revolution."],
["mcqueen","Alexander McQueen",6,"Poverty; industry cruelty","1990s","Dark romanticism."],
["abloh","Virgil Abloh",6,"Outsider in fashion","2000s","Off-White to LV."],
["warhol2","Andy Warhol",6,"Illustrator stigma","1950s","Factory model."],
["basquiat2","Jean-Michel Basquiat",6,"SAMO poverty","1970s","Boom and exploitation."],
["kahlo2","Frida Kahlo",6,"Bus accident","1925","Art from destroyed body."],
["vangogh","Vincent van Gogh",6,"Sold almost nothing","1880s","Posthumous myth."],
["beethoven2","Ludwig van Beethoven",6,"Deafness","1790s-1820s","Late quartets under silence."],
["mozart2","Wolfgang Amadeus Mozart",6,"Died in debt","1791","Financial chaos."],
["coltrane","John Coltrane",6,"Fired by Miles; addiction","1957","A Love Supreme after recovery."],
["socrates","Socrates",6,"Forced hemlock","399 BC","Questioning as crime."],
["hypatia","Hypatia",6,"Murdered by mob","415","Classical learning’s martyr."],
["malala","Malala Yousafzai",6,"Shot by Taliban","2012","Education after violence."],
["navalny","Alexei Navalny",6,"Poisoned; imprisoned","2020s","Opposition under Putin."],
["havel","Václav Havel",6,"Jailed playwright","1970s-80s","Velvet path to presidency."],
["sakharov","Andrei Sakharov",6,"Internal exile","1980s","Bomb then human rights."],
["jane_jacobs","Jane Jacobs",6,"No degree; fought planners","1960s","Death and Life of cities."],
["zaha","Zaha Hadid",6,"Unbuilt for years","1980s-90s","Parametric late bloom."],
["maya_lin","Maya Lin",6,"Vietnam Memorial controversy","1981","Young designer under fire."],
["freeman2","Morgan Freeman",5,"Broke until ~50","1980s","Late career explosion."],
["quan","Ke Huy Quan",5,"No roles after child stardom","1990s-2020s","Everything Everywhere return."],
["fraser","Brendan Fraser",5,"Injury; industry exile","2000s-20s","The Whale return."],
["pascal","Pedro Pascal",5,"Years of bit parts","1990s-2019","Mandalorian at 45."],
["zendaya","Zendaya",5,"Disney kid stigma","2010s","Euphoria prestige."],
["pee2","Jordan Peele",5,"Comedy to horror risk","2010s","Get Out leap."],
["gerwig2","Greta Gerwig",5,"Typecast as actress","2010s","Lady Bird voice."],
["bigelow2","Kathryn Bigelow",5,"Near Dark ignored","1980s","First woman Best Director."],
["nolan2","Christopher Nolan",5,"Self-funded Following","1990s","Memento leap."],
["chappelle2","Dave Chappelle",5,"Walked from $50M","2005","Return on own terms."],
["rock2","Chris Rock",5,"SNL quiet years","1990s","Bring the Pain."],
["fey","Tina Fey",5,"Writer room sexism","1990s","30 Rock showrunner."],
["poehler","Amy Poehler",5,"Second City poverty","1990s","Parks and Rec."],
["issa","Issa Rae",5,"Unpaid Awkward Black Girl","2010s","Insecure deal."],
["coel","Michaela Coel",5,"Assault; network fights","2010s","I May Destroy You control."],
["waller","Phoebe Waller-Bridge",5,"Rejected pilots","2010s","Fleabag stage to screen."],
["glover","Donald Glover",5,"30 Rock burnout","2010s","Atlanta freedom."],
["ocean","Frank Ocean",5,"Contract wars","2010s","Blond scarcity."],
["tyler","Tyler the Creator",5,"Banned; shock era","2010s","Igor evolution."],
["kendrick","Kendrick Lamar",5,"Industry patience","2010s","To Pimp a Butterfly."],
["nipsey","Nipsey Hussle",5,"Indie grind","2010s","Ownership ethos."],
["mac","Mac Miller",5,"Addiction","2010s","Growth cut short."],
["avicii","Avicii",5,"Mental health","2010s","EDM pressure."],
["chester","Chester Bennington",5,"Depression","2017","Linkin Park voice."],
["britney","Britney Spears",5,"Conservatorship","2008-21","Free Britney."],
["kesha","Kesha",5,"Dr. Luke legal war","2010s","Legal and music survival."],
["rihanna","Rihanna",5,"Abuse; leaving comfort","2009","Fenty empire."],
["oprah3","Oprah Winfrey",5,"Fired from Baltimore TV","1980s","Talk format invention."],
["winfrey_g","Gayle King",5,"Sidekick shadow","1980s-2000s","Own morning seat."],
["wintour","Anna Wintour",6,"Fired from Harper’s","1970s","Vogue power after setbacks."],
["ralph2","Ralph Lauren",6,"Ties rejected","1960s","Lifestyle brand."],
["armani","Giorgio Armani",6,"Late start at 40","1970s","Soft tailoring empire."],
["ford_t","Tom Ford",6,"Gucci near bankruptcy","1990s","Turnaround glamour."],
["lamarr","Hedy Lamarr",3,"Invention ignored","1940s","Frequency hopping foundational later."],
["carver","George Washington Carver",3,"Born enslaved; underfunded","1890s","Crop science communication."],
["borlaug","Norman Borlaug",3,"Early rust setbacks","1940s","Green Revolution."],
["salk","Jonas Salk",3,"No patent; later struggles","1950s","Polio vaccine priority."],
["grandin","Temple Grandin",3,"Autism stigma","1970s","Livestock design revolution."],
["dweck","Carol Dweck",3,"Early fixed-mindset student","1960s","Growth mindset research."],
["kahneman","Daniel Kahneman",3,"Psych not real to economists","1970s","Prospect theory long road."],
["thaler","Richard Thaler",3,"Nudge mocked","1980s-2000s","Behavioral economics."],
["taleb","Nassim Taleb",3,"Essayist hostility","2000s","Skin in the game."],
["rosling","Hans Rosling",3,"Data ignored","2000s","Factfulness communication."],
["meadows","Donella Meadows",3,"Limits to Growth attacks","1970s","Systems thinking."],
["jung","Carl Jung",3,"Split from Freud; breakdown","1910s","Analytical psychology from crisis."],
["skinner","B.F. Skinner",3,"Beyond Freedom attacks","1970s","Behaviorism wars."],
["montessori","Maria Montessori",3,"Medical and gender barriers","1900s","Education method."],
["duckworth","Angela Duckworth",3,"Early teaching struggles","1990s","Grit research origin."],
["silver","Nate Silver",3,"Forecasting skepticism","2000s","From baseball to politics."],
["smil","Vaclav Smil",3,"Energy realism unpopular","1990s-2010s","Growth limits analysis."],
["farmer","Paul Farmer",3,"Funding fights","1980s","Partners In Health."],
["gawande","Atul Gawande",3,"Early surgical errors admitted","1990s","Checklist manifesto."],
["sanger_f","Fred Sanger",3,"Near exit from science","1940s","Two Nobels in chemistry."],
["venter","Craig Venter",3,"Celera hostility","1990s","Shotgun sequencing bet."],
["doudna","Jennifer Doudna",3,"CRISPR IP wars","2010s","Science under patents."],
["charpentier","Emmanuelle Charpentier",3,"Mobile career instability","2000s","CRISPR partnership."],
["yonath","Ada Yonath",3,"Ribosome doubt for years","1980s-2000s","Nobel after wilderness."],
["hodgkin","Dorothy Hodgkin",3,"Chronic health","1940s-60s","Penicillin and B12 structures."],
["meitner","Lise Meitner",3,"Fled Nazis; no Nobel","1930s-40s","Fission credit politics."],
["wu","Chien-Shiung Wu",3,"Excluded from Nobel","1950s","Parity experiment."],
["bell_burnell","Jocelyn Bell Burnell",3,"Pulsar credit to supervisor","1967","Overlooked discoverer."],
["stevens","Nettie Stevens",3,"Undercredited","1900s","Chromosomal sex determination."],
["tu2","Tu Youyou",3,"No PhD; harsh conditions","1960s-70s","Artemisinin."],
["job_s2","Steve Jobs",0,"Ousted from Apple","1985","NeXT and Pixar then return."],
["musk3","Elon Musk",0,"2008 near death","2008","Tesla and SpaceX brink."],
["gates2","Bill Gates",0,"Traf-O-Data flop","1970s","First company failed."],
["ma2","Jack Ma",0,"Job rejections","1980s","KFC and exams."],
["bezos2","Jeff Bezos",0,"Years of losses","1990s","Amazon skepticism."],
["sanders2","Colonel Sanders",1,"1000+ recipe nos","1950s","Franchise in his 60s."],
["ford2","Henry Ford",1,"Two failed car cos","1899-1908","Third attempt Model T."],
["dyson3","James Dyson",1,"5126 prototypes","1978-93","Manufacturers said no."],
["rowling3","J.K. Rowling",2,"12 publisher nos","1995-97","Benefits then Harry Potter."],
["king3","Stephen King",2,"Carrie in the trash","1973","Wife rescued the draft."],
["seuss2","Dr. Seuss",2,"27 rejections","1937","Sidewalk meeting."],
["edison2","Thomas Edison",3,"1000+ bulb attempts","1879","Each failure as data."],
["einstein2","Albert Einstein",3,"Labeled slow","late 1800s","Patent clerk years."],
["disney2","Walt Disney",5,"Fired; bankrupt","1920s","Imagination critique."],
["spielberg3","Steven Spielberg",5,"USC rejected","1960s","Learned on lots."],
["beatles2","The Beatles",5,"Decca rejection","1962","Guitar groups on the way out."],
["jobs_pixar","Steve Jobs (Pixar)",0,"NeXT hardware struggle","1985-97","Software and story saved."],
["hoffman3","Reid Hoffman",0,"SocialNet failed","1997-2002","LinkedIn after miss."],
["thiel2","Peter Thiel",1,"Clarium struggles","2000s","Macro fund underperformed."],
["altman2","Sam Altman",1,"Loopt modest","2005-12","Before YC and OpenAI."],
["collison","Patrick Collison",0,"Teen software ignored","2000s","Stripe after credibility gap."],
["spiegel2","Evan Spiegel",0,"Snapchat toy mockery","2011","Investors passed."],
["kroc2","Ray Kroc",1,"Late salesman years","1950s","McDonald’s system scale."],
["hershey2","Milton Hershey",1,"Two candy failures","1880s","Caramel then chocolate."],
["huffington2","Arianna Huffington",1,"Book rejected 36 times","1980s","Platform after print nos."],
["grisham2","John Grisham",2,"First novel rejected","1980s","Kept writing law thrillers."],
["christie2","Agatha Christie",2,"First novel delayed","1916-20","Best-selling novelist."],
["potter2","Beatrix Potter",2,"Publishers said no","1901","Self-published Peter Rabbit."],
["angelou2","Maya Angelou",2,"Years of hardship","1960s","Caged Bird breakthrough."],
["darwin3","Charles Darwin",3,"Delayed 20 years","1830s-59","Fear and evidence."],
["wallace2","Alfred Russel Wallace",3,"Specimens burned at sea","1852","Restarted collecting."],
["oppenheimer2","J. Robert Oppenheimer",3,"Clearance revoked","1954","Political destruction."],
["feynman2","Richard Feynman",3,"Challenger politics","1986","O-ring truth."],
["sagan2","Carl Sagan",3,"Harvard tenure denied","1960s","Communication as duty."],
["ruth2","Babe Ruth",4,"Strikeout record","1910s-30s","Failure in the same swing."],
["gretzky2","Wayne Gretzky",4,"Too small","1970s","Vision over bulk."],
["jock_b","Billie Jean King",4,"Battle of the Sexes pressure","1973","Equality fight."],
["hamm","Mia Hamm",4,"Brother’s death","1980s","Title IX generation."],
["wambach","Abby Wambach",4,"Near-misses","2000s-15","Header legend."],
["rapinoe","Megan Rapinoe",4,"Equal pay fight","2010s","On and off field."],
["felix","Allyson Felix",4,"Maternity fight with Nike","2010s","Most decorated track."],
["shacarri","Sha’Carri Richardson",4,"Suspension","2021","Return under scrutiny."],
["kipchoge","Eliud Kipchoge",4,"Sub-2 attempts","2010s","Marathon margins."],
["astaire2","Fred Astaire",5,"Can’t act note","1930s","Dance elegance."],
["ball2","Lucille Ball",5,"No future in comedy","1930s","I Love Lucy empire."],
["monroe2","Marilyn Monroe",5,"Typecast; studio fights","1940s-50s","Craft under image."],
["wes_anderson","Wes Anderson",5,"Early budget constraints","1990s","Style as system."],
["pt_anderson","Paul Thomas Anderson",5,"Early studio fights","1990s","Autuer persistence."],
["gerwig3","Greta Gerwig",5,"Actor box","2010s","Director voice."],
["peele3","Jordan Peele",5,"Key & Peele then risk","2010s","Social thriller."],
["bong","Bong Joon-ho",5,"Korean cinema limits","2000s","Parasite global."],
["kurosawa2","Akira Kurosawa",5,"Unfashionable years","1970s","Ran late."],
["miyazaki3","Hayao Miyazaki",5,"Retirement returns","1990s-2020s","Cannot quit craft."],
["lynch_d","David Lynch",5,"Dune failure","1984","Twin Peaks rebirth."],
["scott_r","Ridley Scott",5,"Blade Runner misunderstood","1982","Director’s cut vindication."],
["nolan3","Christopher Nolan",5,"Following maxed cards","1990s","Independent start."],
["villeneuve","Denis Villeneuve",5,"Early Canadian limits","2000s","Dune scale later."],
["jenkins","Barry Jenkins",5,"Years before Moonlight","2010s","Medicine for Melancholy path."],
["duvernay","Ava DuVernay",5,"Publicist to director","2000s","Selma then ownership."],
["gerwig4","Chloe Zhao",5,"Indie poverty years","2010s","Nomadland Oscar."],
["zhao","Chloé Zhao",5,"Studio vs indie tension","2020s","Eternals reception."],
["waithe","Lena Waithe",5,"Years before Emmy","2010s","Master of None."],
["rhimes","Shonda Rhimes",5,"Grey’s backlash","2000s","Netflix ownership."],
["murphy_r","Ryan Murphy",5,"Network constraints","2000s","Producer empire."],
["oliver","John Oliver",5,"Sidekick years","2010s","Longform comedy news."],
["stewart","Jon Stewart",5,"Failed talk shows","1990s","Daily Show peak."],
["colbert","Stephen Colbert",5,"Character then real seat","2010s","Late Show transition."],
["noah","Trevor Noah",5,"Successor pressure","2015","Born a Crime path."],
["burnham","Bo Burnham",5,"Viral teen then panic","2010s","Inside pandemic."],
["gadsby","Hannah Gadsby",5,"Industry hostility","2010s","Nanette reset."],
["notaro","Tig Notaro",5,"Cancer set live","2012","Honesty as form."],
["mulaney","John Mulaney",5,"Relapse public","2020","Rebuilding act."],
["birbiglia","Mike Birbiglia",5,"Sleepwalking injury","2000s","Story monologue."],
["oswalt","Patton Oswalt",5,"Grief","2016","Comedy through mourning."],
["rock3","Chris Rock",5,"Oscals slap moment","2022","Public recalibration."],
["smith_w","Will Smith",5,"Oscars slap","2022","Career hit after peak."],
["spacey","Kevin Spacey",5,"Accusations exile","2017","House of Cards fall."],
["cosby","Bill Cosby",5,"Fallen image","2010s","American dad myth end."],
["weinstein","Harvey Weinstein",5,"Criminal exposure","2017","Systemic reckoning."],
["rkelly","R. Kelly",5,"Decades then conviction","2010s","Enablement lesson."],
["jackson_m","Michael Jackson",5,"Trials; finances","1990s-2009","Thriller vs later life."],
["houston_w","Whitney Houston",5,"Addiction","1990s-2012","Voice under drugs."],
["aretha2","Aretha Franklin",5,"Columbia miscasting","1960s","Atlantic Respect."],
["wonder2","Stevie Wonder",5,"Motown control fights","1960s","1970s classics."],
["marley2","Bob Marley",5,"Assassination attempt","1976","Global after exile."],
["cash","Johnny Cash",5,"Addiction; Folsom","1960s","Man in Black rebirth."],
["nelson","Willie Nelson",5,"Nashville rejection","1960s","Outlaw country."],
["parton","Dolly Parton",5,"Poverty; split","1960s","Business and songcraft."],
["springsteen2","Bruce Springsteen",5,"Legal freeze","1970s","Darkness after Born to Run."],
["floyd","Pink Floyd",5,"Syd Barrett collapse","1960s","Wish You Were Here."],
["zeppelin","Led Zeppelin",5,"Critical scorn early","1960s","Album model power."],
["stones","Rolling Stones",5,"Raids; Brian Jones death","1960s","Longevity machine."],
["queen2","Queen",5,"Early poor sales","1970s","Bohemian myth."],
["elton","Elton John",5,"Addiction; closet pressure","1970s","Farewell craft."],
["mercury","Freddie Mercury",5,"AIDS secrecy","1980s","Stage under illness."],
["bach2","J.S. Bach",6,"Old-fashioned at death","1750","Rediscovery later."],
["michelangelo2","Michelangelo",6,"Forced projects; rivals","1500s","Sistine under pressure."],
["rodin2","Auguste Rodin",6,"Failed Beaux-Arts thrice","1850s","Modern sculpture."],
["monet2","Claude Monet",6,"Poverty; mocked","1870s","Impressionism rejected."],
["picasso2","Pablo Picasso",6,"Blue Period poverty","1901-04","Near starvation Paris."],
["matisse2","Henri Matisse",6,"Fauvism attacked","1905","Wild beast label."],
["pollock2","Jackson Pollock",6,"Alcohol; late recognition","1940s","Action painting."],
["ono","Yoko Ono",6,"Beatles blame; scorn","1960s","Avant-garde arc."],
["abramovic","Marina Abramović",6,"Body art dismissed","1970s","Performance endurance."],
["banksy2","Banksy",6,"Arrest risk","1990s","Anonymous model."],
["fairey","Shepard Fairey",6,"Arrests; HOPE lawsuit","2000s","Street to campaign."],
["christo2","Christo",6,"Permits denied decades","1960s-2000s","Wrapped patience."],
["pei","I.M. Pei",6,"Louvre pyramid hostility","1980s","Then acceptance."],
["kere","Diébédo Francis Kéré",6,"Resource constraints","1990s","Local material architecture."],
["koolhaas","Rem Koolhaas",6,"Early unbuilt losses","1970s","Theory as practice."],
["ingels","Bjarke Ingels",6,"Crisis cancellations","2000s","Yes is More rebound."],
["wright_fl","Frank Lloyd Wright",6,"Scandals; fires","1910s","Architecture rebirths."],
["moses","Robert Moses",6,"Later backlash","1960s","Builder then villain."],
["trotsky","Leon Trotsky",6,"Exiled; assassinated","1929-40","Revolution’s loser."],
["marx","Karl Marx",6,"London poverty","1840s-80s","Children died; theory under ruin."],
["locke","John Locke",6,"Exile under suspicion","1680s","Toleration abroad."],
["hobbes","Thomas Hobbes",6,"Fled civil war","1640s","Leviathan in exile."],
["machiavelli","Niccolò Machiavelli",6,"Tortured; exiled","1513","Power from outside."],
["confucius","Confucius",6,"No lasting office","500s BC","Teaching over power."],
["cicero","Cicero",6,"Proscribed; killed","43 BC","Republic’s last voice."],
["seneca","Seneca",6,"Ordered suicide","65","Stoicism under Nero."],
["luther","Martin Luther",6,"Excommunicated","1521","Reformation under ban."],
["more","Thomas More",6,"Executed","1535","Conscience vs crown."],
["joan","Joan of Arc",6,"Burned at stake","1431","Symbol after failure of protection."],
["napoleon2","Napoleon",6,"Waterloo; exile twice","1815","Corsican outsider end."],
["hannibal","Hannibal",6,"Never took Rome","200s BC","Brilliance without final win."],
["washington","George Washington",6,"Early military failures","1750s","Then revolutionary command."],
["hamilton_a","Alexander Hamilton",6,"Illegitimate; duels","1770s-1804","Immigrant founder arc."],
["burr","Aaron Burr",6,"Killed Hamilton; treason trial","1804","Fallen founder."],
["douglass","Frederick Douglass",6,"Escaped slavery","1830s","Orator after bondage."],
["tubman","Harriet Tubman",6,"Injured; hunted","1850s","Underground Railroad."],
["truth","Sojourner Truth",6,"Enslaved; court fights","1800s","Ain’t I a Woman path."],
["wells","Ida B. Wells",6,"Threats; office destroyed","1890s","Anti-lynching journalism."],
["du_bois","W.E.B. Du Bois",6,"NAACP fights; exile","1900s-60s","Pan-African late years."],
["garvey","Marcus Garvey",6,"Imprisoned; deported","1920s","UNIA rise and fall."],
["parks","Rosa Parks",6,"Arrested","1955","Bus boycott spark."],
["lewis_j","John Lewis",6,"Beaten on bridge","1965","Good trouble lifelong."],
["baker","Ella Baker",6,"Overlooked organizer","1950s-60s","Grassroots over charisma."],
["chavez","Cesar Chavez",6,"Fasting; grower wars","1960s","Farm worker movement."],
["huerta","Dolores Huerta",6,"Beaten; sidelined","1960s","Sí se puede co-founder."],
["steinem","Gloria Steinem",6,"CIA funding smear","1970s","Feminist organizing under attack."],
["friedan","Betty Friedan",6,"Suburban mystique scorn","1960s","Feminine Mystique storm."],
["sanger_m","Margaret Sanger",6,"Jailed for birth control","1910s","Clinic raids."],
["anthony","Susan B. Anthony",6,"Arrested for voting","1872","Suffrage long war."],
["stanton","Elizabeth Cady Stanton",6,"Ridiculed Seneca Falls","1848","Declaration of Sentiments."],
["addams","Jane Addams",6,"Pacifism attacks","WWI","Hull House under fire."],
["keller","Helen Keller",6,"Deaf-blind; socialist smear","1900s","Radical after miracle story."],
["roosevelt_e","Eleanor Roosevelt",6,"Personal trials","1900s","UN human rights."],
["perkins","Frances Perkins",6,"Sexism in cabinet","1930s","Labor Secretary firsts."],
["rankin","Jeannette Rankin",6,"Voted against both wars","1917-41","Pacifist in Congress."],
["chisholm","Shirley Chisholm",6,"Unbought and unbossed","1968-72","Presidential run barriers."],
["jordan_b","Barbara Jordan",6,"Segregated Texas","1960s","Constitutional voice."],
["abzug","Bella Abzug",6,"Hats and hostility","1970s","Congress and peace."],
["ginsburg","Ruth Bader Ginsburg",6,"Law firm rejections","1950s","ACLU path to Court."],
["oconnor","Sandra Day O’Connor",6,"No firm would hire","1950s","First woman Justice."],
["sotomayor","Sonia Sotomayor",6,"Diabetes; projects","1960s-80s","Princeton to Court."],
["jackson_k","Ketanji Brown Jackson",6,"Confirmation fire","2022","First Black woman Justice."],
["harris","Kamala Harris",6,"Early primary exit","2020","VP after failed presidential."],
["warren","Elizabeth Warren",6,"Primary loss","2020","Consumer agency after crisis."],
["sanders_b","Bernie Sanders",6,"Long-shot socialist","2016-20","Movement without nomination."],
["aoc2","Alexandria Ocasio-Cortez",6,"Bartender long-shot","2018","Primary upset."],
["bowman","Jamaal Bowman",6,"Primary loss after rise","2024","Squad volatility."],
["cori","Cori Bush",6,"Primary loss","2024","Activist to Congress to out."],
["trump","Donald Trump",6,"Casino bankruptcies","1990s","Business failures before politics."],
["romney","Mitt Romney",6,"2012 loss","2012","Massachusetts to national."],
["mccain","John McCain",6,"POW; 2000 and 2008 losses","1967-2008","Maverick narrative."],
["goldwater","Barry Goldwater",6,"1964 landslide loss","1964","Movement conservatism seed."],
["humphrey","Hubert Humphrey",6,"1968 loss","1968","Vietnam split."],
["mondale","Walter Mondale",6,"1984 landslide","1984","49-state loss."],
["dukakis","Michael Dukakis",6,"1988 tank photo","1988","Campaign collapse."],
["gore","Al Gore",6,"2000 election","2000","Popular vote without office."],
["kerry","John Kerry",6,"2004 loss","2004","Swift boat attacks."],
["clinton_h","Hillary Clinton",6,"2016 loss","2016","Emails and rust belt."],
["clinton_b","Bill Clinton",6,"1994 midterms; impeachment","1990s","Comebacks and scars."],
["bush_w","George W. Bush",6,"Failed oil; 1994 loss talk","1970s-90s","Governor then war presidency."],
["bush_h","George H.W. Bush",6,"1992 loss","1992","Read my lips."],
["reagan2","Ronald Reagan",6,"Acting plateau; 1976 primary","1950s-76","Late political rise."],
["carter3","Jimmy Carter",6,"Hostage crisis","1979-80","One-term then humanitarian."],
["ford_g","Gerald Ford",6,"Pardon fallout","1974-76","Unelected then defeated."],
["nixon3","Richard Nixon",6,"Watergate","1974,"Resignation."],
["johnson_l","Lyndon Johnson",6,"Vietnam","1968","Chose not to run."],
["kennedy2","John F. Kennedy",6,"PT-109; health","WWII","Near-death and illness."],
["eisenhower","Dwight Eisenhower",6,"Heart; late entry","1950s","General to president."],
["truman3","Harry Truman",6,"Dewey beats Truman","1948","Upset win after doubt."],
["fdr3","Franklin Roosevelt",6,"Court packing fight","1937","Limits of mandate."],
["hoover","Herbert Hoover",6,"Depression blame","1929-33","Engineering success to political ruin."],
["coolidge","Calvin Coolidge",6,"Son’s death","1924","Silent under grief."],
["harding","Warren Harding",6,"Scandals","1923","Teapot Dome."],
["wilson","Woodrow Wilson",6,"Stroke; League failure","1919","Broken body and treaty."],
["taft","William Howard Taft",6,"1912 split loss","1912","Friendship with TR broken."],
["teddy2","Theodore Roosevelt",6,"Wife and mother same day","1884","Ranch exile then return."],
["mckinley","William McKinley",6,"Assassinated","1901","Peak then death."],
["cleveland","Grover Cleveland",6,"Non-consecutive terms","1880s-90s","Lost then regained."],
["grant3","Ulysses Grant",6,"Presidency scandals","1870s","War hero to tainted admin."],
["johnson_a","Andrew Johnson",6,"Impeached","1868","Reconstruction fights."],
["lincoln4","Abraham Lincoln",6,"Civil War losses","1861-65","Before Gettysburg."],
["buchanan","James Buchanan",6,"Secession on watch","1860","Worst ranked often."],
["pierce","Franklin Pierce",6,"Son died; alcohol","1850s","Broken presidency."],
["fillmore","Millard Fillmore",6,"Know-Nothing late turn","1850s","Compromise then decline."],
["taylor","Zachary Taylor",6,"Died in office","1850","Short presidency."],
["polk","James K. Polk",6,"Overwork; early death","1849","Promises kept then gone."],
["tyler","John Tyler",6,"Party exile","1841","President without a party."],
["harrison_w","William Henry Harrison",6,"Died after 31 days","1841","Longest speech."],
["van_buren","Martin Van Buren",6,"Panic of 1837","1837","Economic collapse."],
["jackson_a","Andrew Jackson",6,"Duel wounds; wife’s death","1800s","Personal and political violence."],
["adams_j","John Quincy Adams",6,"1828 loss","1828","Corrupt bargain charge."],
["monroe_j","James Monroe",6,"Near-empty treasury wars","1810s","Era of good feelings after."],
["madison","James Madison",6,"White House burned","1814","War of 1812 humiliation."],
["jefferson","Thomas Jefferson",6,"Debt; Sally Hemings","1800s","Ideals vs private life."],
["adams","John Adams",6,"Alien acts; loss to Jefferson","1790s","Bitter retirement."],
["washington2","George Washington",6,"Early war retreats","1776","Crossing after defeats."]
];
var colors=["#0ea5e9","#8b5cf6","#22c55e","#f59e0b","#ef4444","#06b6d4","#ec4899","#a855f7","#14b8a6","#f43f5e","#7c3aed","#eab308","#0d9488","#f97316","#3b82f6","#10b981","#dc2626","#2563eb","#9333ea","#c026d3"];
window.FAILURES=(window.FAILURES||[]).concat(R.map(function(r,i){
var id=r[0],name=r[1],cat=C[r[2]]||C[0],fail=r[3],year=r[4],story=r[5];
var initials=name.split(/\s+/).map(function(w){return w.charAt(0)}).join("").slice(0,3).toUpperCase();
return{id:id,name:name,initials:initials,color:colors[i%colors.length],category:cat,fail:fail,year:year,story:story,whatTheyDid:story,apply:["Write a short post-mortem: what broke, what you control next.","Change one input before the next attempt.","Keep minimum weekly output while recovering."],scenariosYes:["After a setback in this field"],scenariosNo:["When craft is still unexamined"],resources:["Time","Feedback partner","Post-mortem"],takeaway:"Failure is tuition only if you change the method.",book:name+" — biography / profiles",bookGain:"Patterns from "+name+"'s path through setback."};
}));
})();
