#!/usr/bin/env python3
"""
generate_real_cases.py
Converts scripts/real_cases.py (curated hand-written specific failure events)
into people-failures/real-cases.js, which exposes window.REAL_CASES.

Unlike the previous synthetic catalog, every entry here is a real, documented
historical failure event with a hand-written story, takeaway, and book
recommendation. No templates, no facets, no synthetic combinations.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from real_cases import REAL_CASES, CATEGORIES

OUT_DIR = Path(__file__).parent.parent / "people-failures"

CATEGORY_COLORS = {
    "Technology": "#0ea5e9",
    "Business": "#a78bfa",
    "Companies": "#f43f5e",
    "Products": "#06b6d4",
    "Games": "#a855f7",
    "Films": "#eab308",
    "Projects": "#84cc16",
    "Literature": "#f472b6",
    "Science": "#34d399",
    "Sports": "#fb923c",
    "Entertainment": "#facc15",
    "Politics & Fashion": "#94a3b8",
}

def initials_for(name):
    parts = [p for p in name.replace("-", " ").replace("—", " ").split() if p and not p.startswith("(")]
    if not parts:
        return "?"
    if len(parts) == 1:
        return parts[0][:2].upper()
    return (parts[0][0] + parts[-1][0]).upper()

def build_entry(case):
    # case = (id, name, cat_idx, fail, year, whatTheyDid, story, book, takeaway)
    sid, name, cat_idx, fail, year, what, story, book, takeaway = case
    cat = CATEGORIES[cat_idx]
    color = CATEGORY_COLORS.get(cat, "#6b7280")
    return {
        "id": sid,
        "name": name,
        "initials": initials_for(name),
        "color": color,
        "category": cat,
        "fail": fail,
        "year": year,
        "story": story,
        "whatTheyDid": what,
        "apply": [
            "Read the post-mortem in writing — most teams skip it and repeat the failure.",
            "Separate the narrative failure from the unit-economics failure — they require different fixes.",
            "Ask who had incentive to ignore early warnings — the answer explains the latency of response.",
        ],
        "scenariosYes": [
            "When a similar crisis is approaching",
            "When planning the next major decision in this category",
        ],
        "scenariosNo": [
            "When the context has materially changed",
        ],
        "resources": [
            "The primary post-mortem document",
            "The book or long-form reporting below",
            "A peer who has navigated a similar situation",
        ],
        "takeaway": takeaway,
        "book": book,
        "bookGain": "How this specific failure unfolded publicly — patterns that translate across categories.",
        "real": True,  # explicit flag — this is hand-curated, real, specific
    }

def main():
    # Load image map if it exists (populated by fetch_wiki_images.py)
    img_map_path = Path(__file__).parent / "wiki_img_map.json"
    img_map = {}
    if img_map_path.exists():
        img_map = json.loads(img_map_path.read_text())
        found = sum(1 for v in img_map.values() if v)
        print(f"[gen] loaded image map: {found}/{len(img_map)} entries have images", file=sys.stderr)

    entries = [build_entry(c) for c in REAL_CASES]

    # Attach image URLs from the map
    for e in entries:
        if e["id"] in img_map and img_map[e["id"]]:
            e["img"] = img_map[e["id"]]

    # De-duplicate by ID (defensive; the source should already be unique)
    seen = set()
    deduped = []
    dups = []
    for e in entries:
        if e["id"] in seen:
            dups.append(e["id"])
            continue
        seen.add(e["id"])
        deduped.append(e)
    if dups:
        print(f"[gen] dropped duplicate IDs: {sorted(set(dups))}", file=sys.stderr)

    # Also filter out IDs already in data.js hero set
    hero_path = OUT_DIR / "data.js"
    if hero_path.exists():
        import re
        text = hero_path.read_text(encoding="utf-8")
        hero_ids = set(re.findall(r'id:\s*"([^"]+)"', text))
        hero_ids |= set(re.findall(r"id:\s*'([^']+)'", text))
        before = len(deduped)
        deduped = [e for e in deduped if e["id"] not in hero_ids]
        skipped = before - len(deduped)
        if skipped:
            print(f"[gen] skipped {skipped} entries already in data.js", file=sys.stderr)

    out_path = OUT_DIR / "real-cases.js"
    with out_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/generate_real_cases.py — do not edit by hand.\n")
        f.write(f"// {len(deduped)} REAL documented specific failure events with hand-written playbooks.\n")
        f.write("// Image URLs sourced from Wikipedia/Wikimedia Commons via fetch_wiki_images.py.\n")
        f.write("// Entries without an `img` field fall back to the initials avatar.\n")
        f.write("// No synthetic data. No templated content. Every entry corresponds to a real\n")
        f.write("// historical event that is documented in primary reporting or scholarly literature.\n")
        f.write("window.FAILURES = (window.FAILURES||[]).concat(")
        f.write(json.dumps(deduped, ensure_ascii=False, separators=(",", ":")))
        f.write(");\n")
    size_kb = out_path.stat().st_size / 1024
    print(f"[gen] wrote {out_path} — {len(deduped)} real cases, {size_kb:.1f} KB")
    img_count = sum(1 for e in deduped if e.get("img"))
    print(f"[gen] {img_count}/{len(deduped)} entries have image URLs ({100*img_count//len(deduped)}%)")

if __name__ == "__main__":
    main()
